<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder {

    /**
     * Seed the application's database.
     *
     * @return void
     */
    // const DESCPROD = '<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem. Phasellus pellentesque. Mauris quam enim, molestie in, rhoncus ut, lobortis a, est. </p><p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem. Phasellus pellentesque. Mauris quam enim, molestie in, rhoncus ut, lobortis a, est.</p>';

    public function run() {

        DB::table('categoria')->insert([
            ['nome' => 'Computer'],
            ['nome' => 'Display'],
            ['nome' => 'Dispositivi Mobile'],
            ['nome' => 'Foto e Video'],
        ]);
        DB::table('sottocategoria')->insert([
            ['nome' => 'Fotocamere', 'categoria' => 'Foto e Video'],
            ['nome' => 'Videocamere', 'categoria' => 'Foto e Video'],
            ['nome' => 'Action cam', 'categoria' => 'Foto e Video'],
            ['nome' => 'Treppiedi', 'categoria' => 'Foto e Video'],
            ['nome' => 'Tablet', 'categoria' => 'Dispositivi Mobile'],
            ['nome' => 'Smartphone', 'categoria' => 'Dispositivi Mobile'],
            ['nome' => 'Laptop', 'categoria' => 'Computer'],
            ['nome' => 'Desktop', 'categoria' => 'Computer'],
            ['nome' => 'TV', 'categoria' => 'Display'],
            ['nome' => 'Monitor', 'categoria' => 'Display'],
        ]);
        DB::table('prodotto')->insert([
        ['prezzo' => 470.00,
        'nome' => 'Nikon D3500',
        'desc_breve' => 'Nikon D3500 Fotocamera Reflex Digitale con Obiettivo Nikkor AF-P 18-55, F/3.5-5.6G VR DX',
        'desc_esaustiva' => 'Nikon D3500: fotografa, riprendi video, condividi, divertiti, stupisci. La nuova reflex digitale \"entry level\" da 24,2 Megapixel è la fotocamera perfetta per chi si avvicina al mondo della fotografia, in virtù del suo design confortevole e delle sue modalità di ripresa che ne rendono facilissimo l\'uso. In più, con Nikon SnapBridge condividere immediatamente le immagini straordinarie che vengono realizzate è facilissimo: impossibile non farlo. Versatile kit con obiettivo zoom per eccezionali fotografie di tutti i giorni. Include la fotocamera D3500, nonché il compatto obiettivo con zoom AF-P DX NIKKOR 18–55mm VR. L\'obiettivo di questo kit assicura una veloce e fluida messa a fuoco, ideale per le riprese di filmati con la quasi totale eliminazione del disturbo meccanico. Lo straordinario sistema di riduzione vibrazioni di Nikon garantisce la nitidezza delle foto anche in condizioni di scarsa illuminazione.',
        'sconto' => 10,
        'marca' => 'Nikon',
        'immagine' => '1.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 429.00,
        'nome' => 'Nikon D3300',
        'desc_breve' => 'Nikon D3500 Fotocamera Reflex Digitale con Obiettivo Nikkor AF-P 18-55, F/3.5-5.6G VR DX',
        'desc_esaustiva' => 'Catturate la vera atmosfera dei momenti importanti con la fotocamera D3300 Potente, comoda da trasportare e di facilissimo utilizzo, questa D-SLR da 24.2 megapixel, piccola e leggera, è un ottimo modo per riprendere indimenticabili foto e filmati ad alta definizione.Il Modo guida fornisce assistenza passo-passo a coloro che si avvicinano per la prima volta alla fotografia D-SLR o a chi desidera ulteriori informazioni, utilizzando immagini di esempio e istruzioni chiare per mostrarvi come scattare foto e riprendere filmati fantastici.Per chi vuole condividere, l\'adattatore wireless per la comunicazione con dispositivi mobili di Nikon semplifica il caricamento di foto nei siti preferiti tramite uno smart device.Riprendete immagini chiare con qualsiasi tipo di luce. Il processore di elaborazione delle immagini di Nikon, rapido e potente, garantisce un funzionamento veloce e funzioni avanzate di riduzione disturbo, per ottenere immagini estremamente nitide con colori naturali in qualsiasi condizione di illuminazione.È possibile riprendere le azioni alla rapida cadenza di 5 fotogrammi al secondo e catturare movimenti ed espressioni fugaci esattamente al momento giusto.Obiettivo zoom in formato DX compatto e leggero per eccezionali scatti di vita quotidiana. Con una portata dello zoom da grandangolare a normale e una struttura compatta, è l\'obiettivo ideale per scattare tra la gente. È sempre pronto a mettere a fuoco una grande varietà di soggetti, da scatti urbani ai paesaggi fino a eventi sportivi e a filmati HD pieni d\'azione. Qualunque sia il soggetto, il sistema di riduzione vibrazioni di Nikon garantisce la nitidezza delle immagini anche in condizioni di scarsa illuminazione. Il design snello dell\'obiettivo assicura compattezza e comodità di trasporto.',
        'sconto' => '',
        'marca' => 'Nikon',
        'immagine' => '2.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 334.99,
        'nome' => 'Nikon Coolpix B500',
        'desc_breve' => 'Nikon Coolpix B500 Fotocamera Digitale Compatta, 16 Megapixel, Zoom 40X, ISO 125 - 6.400, VR, LCD',
        'desc_esaustiva' => 'Esplorate la potenza dello zoom ottico NIKKOR 40x, estendibile a Dynamic Fine Zoom¹ 80x, mettendovi al centro dell\'azione, con il controllo zoom laterale che assicura una superba stabilità. Scattate foto da un punto di vista esclusivo con il monitor LCD inclinabile ad alta definizione, catturate di nuovo i soggetti con facilità con il pulsante ripristina posizione zoom e mantenete connessa la fotocamera allo smart device con SnapBridge. Il funzionamento intuitivo semplifica le riprese e le funzioni utilizzate di frequente sono accessibili dalla ghiera di selezione modo, mentre il design classico assicura la maneggevolezza necessaria. La COOLPIX B500 da 16 megapixel consente di catturare i momenti della vita da una prospettiva creativa. ZOOM OTTICO NIKKOR 40X Catturate tutta l\'azione degli eventi sportivi, riprendete soggetti distanti con nitidi dettagli in ambientazioni urbane o scattate immagini incredibilmente nitide della luna o del cielo notturno con l\'obiettivo zoom ottico NIKKOR 40x, estendibile a Dynamic Fine Zoom¹ 80x. Le affidabili ottiche NIKKOR garantiscono prestazioni eccezionali e potrete utilizzare un potente obiettivo con angoli di campo dalla copertura grandangolare di 22,5 mm al super teleobiettivo da 900 mm (equivalente alle lunghezze focali nel formato 35 mm) in una fotocamera compatta.',
        'sconto' => '',
        'marca' => 'Nikon',
        'immagine' => '3.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 584.39,
        'nome' => 'Nikon Coolpix P900',
        'desc_breve' => 'Nikon Coolpix P900 Fotocamera Digitale Compatta, Sensore CMOS 16 Megapixel, Zoom 83X, VR, LCD 3", Full HD, Wi-Fi, GPS, GLONASS, QZSS, Nero [Nital Card: 4 Anni di Garanzia]',
        'desc_esaustiva' => 'L\'incredibile zoom ottico 83x della COOLPIX P900 a 16 megapixel consente ai fotografi appassionati di riprese naturalistiche o di cieli notturni di catturare dettagli non visibili a occhio nudo. Eseguite riprese istantanee con AF rapido e un ritardo allo scatto inferiore, mentre il sistema VR ottico a doppio rilevamento con un tempo di posa di 5,0 stop riduce ulteriormente l\'effetto mosso. Composizioni flessibili con il monitor ad angolazione variabile e il mirino elettronico incorporato per riprendere immagini fisse dettagliate con il super teleobiettivo e filmati Full HD. Il supporto GPS/GLONASS/QZSS incorporato localizza le posizioni di scatto e le immagini possono essere condivise immediatamente grazie al Wi-Fi¹ integrato e al supporto NFC². La COOLPIX P900, dal design modellato per garantire riprese agevoli, vi avvicina più che mai alla bellezza della natura.',
        'sconto' => '',
        'marca' => 'Nikon',
        'immagine' => '4.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 482.5,
        'nome' => 'Nikon Coolpix B500 ',
        'desc_breve' => 'Nikon Coolpix B500 Fotocamera Digitale Bridge, 16 Megapixel, Zoom 83X, VR, LCD 3", Full HD, Wi-Fi ',
        'desc_esaustiva' => 'Meravigliosa qualità dell\'immagine con semplicità grazie alla Nikon COOLPIX B500. Esplorate la potenza dello zoom ottico NIKKOR 40x, estendibile a Dynamic Fine Zoom¹ 80x, mettendovi al centro dell\'azione, con il controllo zoom laterale che assicura una superba stabilità. Scattate foto da un punto di vista esclusivo con il monitor LCD inclinabile ad alta definizione, catturate di nuovo i soggetti con facilità con il pulsante ripristina posizione zoom e mantenete connessa la fotocamera allo smart device con SnapBridge. Il funzionamento intuitivo semplifica le riprese e le funzioni utilizzate di frequente sono accessibili dalla ghiera di selezione modo, mentre il design classico assicura la maneggevolezza necessaria. La COOLPIX B500 da 16 megapixel consente di catturare i momenti della vita da una prospettiva creativa.',
        'sconto' => 20,
        'marca' => 'Nikon',
        'immagine' => '5.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 339.99,
        'nome' => 'Canon EOS 2000D ',
        'desc_breve' => 'Canon EOS 2000D + EF-S 18 - 55 mm IS II Fotocamera Reflex, Sensore APS-C da 24.1 megapixel',
        'desc_esaustiva' => 'Crea foto di qualità reflex ricche di dettagli e filmati Full HD cinematografici in tutta semplicità e anche in condizioni di scarsa illuminazione, con EOS 2000D da 24.1 megapixel. Passa a un sensore da 24.1 megapixel che dispone di una superficie fino a 19 volte maggiore rispetto a quella di molti smartphone. Esegui scatti guidati in Live View grazie alla modalità creativa automatica e aggiungi finiture uniche con i filtri creativi. Trasforma i momenti più spontanei in filmati Full HD creativi oppure utilizza la modalità Video Snapshot per catturare i momenti più importanti della tua giornata. Corpo Eos 2000D, Oculare Mirino, Tracolla per Fotocamera Ew-400D, Batteria Lp-E10, Caricabatteria Lc-E10E, Cavo di Alimentazione per Carica Batteria',
        'sconto' => 35,
        'marca' => 'Nikon',
        'immagine' => '6.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 328.00,
        'nome' => 'Canon Italia EOS 4000D ',
        'desc_breve' => 'Canon Italia EOS 4000D + EF-S DC III Fotocamera Reflex, Nero, Lunghezza Focale 18-55 mm',
        'desc_esaustiva' => 'Creare storie uniche con foto di qualità reflex e filmati in Full HD è più semplice di quanto credi con la fotocamera EOS 4000D da 18 megapixel. Scatta immagini splendide con sfondo naturale sfocato in tutta semplicità. Trasforma i momenti di ispirazione in filmati Full HD creativi oppure utilizza la modalità Video Snapshot. Trasferisci istantaneamente foto e filmati sul dispositivo smart per condividerli facilmente sui social media o eseguire il backup sul servizio cloud irista. Corpo Eos 4000D, Oculare Mirino, Tracolla per Fotocamera Ew-400D, Batteria Lp-E10, Caricabatteria Lc-E10E, Cavo di Alimentazione per Carica Batteria',
        'sconto' => 22,
        'marca' => 'Canon',
        'immagine' => '7.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 362.05,
        'nome' => 'Canon Italia PowerShot SX740 ',
        'desc_breve' => 'Canon Italia PowerShot SX740 Fotocamera Digitale Compatta, Nero',
        'desc_esaustiva' => 'L\'esclusivo processore Canon DIGIC 8 gestisce attivamente le impostazioni della fotocamera come Zoom Framing Assist e Hybrid Auto, consentendoti di inquadrare e scattare con risultati incredibili. La spettacolare risoluzione 4K per i filmati e la stabilizzazione a 5 assi consentono di catturare i momenti più belli con dettagli incredibili, anche quando sei in movimento. Non perderti nemmeno un istante grazie alla risposta incredibilmente rapida dell\'otturatore e allo scatto continuo fino a 10 fps. Il Bluetooth, la connessione Wi-Fi e il trasferimento automatico avanzati ti permettono di condividere e archiviare facilmente le foto sul PC di casa o su dispositivi compatibili. Fotocamera digitale PowerShot SX740 HS (BK), cinturino da polso WS-800, batteria NB-13L, carica batteria CB-2LHE, cavo CA (E), kit manuale dell\'utente',
        'sconto' => 13,
        'marca' => 'Canon',
        'immagine' => '8.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 282.13,
        'nome' => 'Canon EOS 1300D ',
        'desc_breve' => 'Canon EOS 1300D Kit Fotocamera Reflex Digitale da 18 Megapixel con Obiettivo EF-S IS II 18-55 mm',
        'desc_esaustiva' => 'Ottieni immagini ricche di dettaglio grazie a un ampio sensore in formato APS-C da 18 megapixel. Stampa le tue immagini fino al formato A2 oppure ritagliale in modo creativo per ottenere risultati di qualità. Scatta foto memorabili anche in condizioni di bassa luce grazie all\'ampia gamma di sensibilità ISO 100-6400 (espandibile fino a ISO 12.800) che ti consente di ridurre la necessità di ricorrere al flash per catturare la vera atmosfera di ogni prezioso ricordo. Con la fotocamera EOS 1300D da 18 megapixel acquisisci facilmente foto di qualità reflex e filmati in Full HD in stile cinematografico. Crea ottimi ritratti che mettono in risalto i tuoi soggetti su sfondi leggermente sfocati grazie alla profondità di campo ridotta tipica della fotografia DSLR. Scatta foto con dettagli, colori e contrasto proprio come li ricordi, grazie al processore DIGIC 4+. Con la tecnologia NFC (Near Field Communication) è possibile collegarsi velocemente a smartphone e tablet Android compatibili e avviare l\'applicazione Camera Connect con un solo tocco. È inoltre possibile collegarsi a dispositivi iOS e non-NFC e avviare l\'applicazione tramite Wi-Fi. Ottimo per un trasferimento rapido e per condividere immagini e filmati in movimento. Trasferisci, memorizza e guarda le tue foto e i tuoi filmati su Canon Connect Station CS100, per una condivisione semplice su un HDTV o su social media e servizi fotografici online come irista.',
        'sconto' => '',
        'marca' => 'Canon',
        'immagine' => '9.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 347.59,
        'nome' => 'Canon EOS 750D  ',
        'desc_breve' => 'Canon EOS 750D Fotocamera Reflex Digitale da 24 Megapixel, Nero/Antracite',
        'desc_esaustiva' => 'Ottieni degli scatti straordinari in qualsiasi situazione grazie al sensore APS-C da 24,2 megapixel e al processore DIGIC 6.. Riprendi facilmente filmati in Full HD di qualità cinematografica con Hybrid CMOS AF III; segue i movimenti e la messa a fuoco tra i soggetti con la massima fluidità.Porta le tue immagini a un livello superiore grazie alla tecnologia reflex di nuova generazione e alla modalità Scena Smart Auto. Condividi i tuoi file online o trasferisci all\'istante le immagini sul tuo dispositivo smart o su Canon Connect Station tramite NFC e Wi-Fi.Contenuto della confezione: Corpo EOS 750D, Oculare mirino, Tappo per fotocamera R-F-3, Tracolla EW-300D, Batteria LP-E17, Sportello del vano batteria, Carica batteria LC-E17, Cavo di alimentazione per carica batteria, Cavo interfaccia IFC-130U, Kit manuale di istruzioni',
        'sconto' => '',
        'marca' => 'Canon',
        'immagine' => '10.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 778.95,
        'nome' => 'Sony Alpha 6300 ',
        'desc_breve' => 'Sony Alpha 6300 Kit Fotocamera Digitale Mirrorless Compatta con Obiettivo Intercambiabile ',
        'desc_esaustiva' => 'Fotocamera compatta con ottiche intercambiabili, sensore Exmor APS-C CMOS da 24.2 MP, processore BIONZ X, ISO 100-51200, mirino XGA OLED 100% copertura (visualizzazione anche a 120fps), Fast hybrid AF (425 punti a rilevamento di fase + 169 a contrasto), 11 fps con AF e 8fps con ritardo ridottissimo di visualizzazione nel mirino/schermo, video 4K interno fino a 30p e Full HD fino a 120p, formato XAVC-S, picture profile, S-log3, S-Gamut 3, corpo in magnesio resistente a polvere e umidità, schermo LCD 3\'\' da 921k punti e whitemagic, wi-fi, NFC, Playmemories Camera Apps, slitta multi-interfaccia, flash integrato, Triluminos Color, Uscita 4K per le foto, batteria NPFW50. Colore nero. Obiettivo SELP1650 F3.5-5.6 OSS.',
        'sconto' => '',
        'marca' => 'Sony',
        'immagine' => '11.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 975.90,
        'nome' => 'Sony Alpha 6400L ',
        'desc_breve' => 'Sony Alpha 6400L Kit Fotocamera Digitale Mirrorless con Obiettivo Intercambiabile SELP 16-50 mm',
        'desc_esaustiva' => 'L\'af più veloce al mondo1 (0,02 sec) combina il meglio dell\'af a rilevamento di fase (425 punti) e a rilevamento di contrasto (425 punti); i punti di messa a fuoco densamente distribuiti coprono l\'84% dell\'area. 1 tra le fotococamere con ottica intercambiabile e sensore aps-c secondo una ricerca sony aggiornata al gennaio 2019. Real-time eye af e real-time tracking grazie alla tecnologia ai di riconoscimento dei soggetti Scatto continuo fino a 11 fps (o 8 fps in silent mode) con af/ae Sensore aps-c exmor cmos da 24.2mp e processore bionz x di ultima generazione. La fotocamera ideale per vloggers e content creators con registrazione video in 4k hdr, fast hybrid af e schermo LCD touch e inclinabile di 180° verso l\'alto (e 74° verso il basso)',
        'sconto' => '',
        'marca' => 'Sony',
        'immagine' => '12.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 990.00,
        'nome' => 'Sony Alpha 6500B ',
        'desc_breve' => 'Sony Alpha 6500B Fotocamera Digitale Mirrorless APS-C ad Obiettivi Intercambiabili',
        'desc_esaustiva' => 'Fotocamera compatta con ottiche intercambiabili, sensore Exmor APS-C CMOS da 24.2 MP, processore BIONZ X e chip d\'acquisizione LSI, stabilizzatore d\'immagine integrato a 5 assi, ISO 100-51200, mirino XGA OLED 100% copertura, Fast hybrid AF (425 punti a rilevamento di fase + 169 a contrasto), velocità di scatto a 11 fps con AF e 8fps con ritardo ridotto di visualizzazione nel mirino/schermo, ampio buffer e scatto continuo fino a 307 scatti, video 4K interno fino a 30p e Full HD fino a 120p, formato XAVC-S, picture profile, S-log3, S-Gamut 3, funzione SlowQuick Motion, corpo in magnesio resistente a polvere e umidità, schermo LCD 3\'\' da 921k punti con funzione touch, Wi-Fi, NFC, compatibilità QR code, Camera Apps, slitta multi-interfaccia, flash integrato, batteria NPFW50. Colore nero.',
        'sconto' => 15,
        'marca' => 'Sony',
        'immagine' => '13.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 899.00,
        'nome' => 'Sony Alpha 7M2K ',
        'desc_breve' => 'Sony Alpha 7M2K Kit Fotocamera Digitale Mirrorless con Obiettivo Intercambiabile SEL 28-70mm',
        'desc_esaustiva' => 'Fotocamera digitale Mirrorless Sony con sensore Full-Frame CMOR Exmor 24.3 megapixel. Kit con obiettivo SEL 28-70 mm F3.5-5.6. Processore di immagini BIONZ X, 117 pt Fast Hybrid AF, 5 fps. ISO 100-51200, otturatore 1/8000-30 sec, batteria NPFW50 350 scatti. Registrazione video FHD 1080p, stabilizzazione integrata a 5 assi. La breve distanza della flangia posteriore negli obiettivi con attacco E dell\'α7 II consente un\'ampia compatibilità',
        'sconto' => '',
        'marca' => 'Sony',
        'immagine' => '14.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 449.00,
        'nome' => 'Sony Alpha 6000L ',
        'desc_breve' => 'Sony Alpha 6000L Kit Fotocamera Digitale Mirrorless con Obiettivo Intercambiabile',
        'desc_esaustiva' => 'Sony Alpha 6000L fotocamera digitale compatta, obiettivo intercambiabile, sensore APS-C CMOS Exmor HD da 24.3 MP, obiettivo da 16-50 mm e nero. Più grande è il sensore e migliori sono le immagini, e l\'α6000 surclassa molte fotocamere della sua categoria. Il sensore APS-C è 1,6 volte più grande dei sensori 4/3 e 13 volte più grande di quelli da 1/2,3\" delle tipiche digitali compatte. Il risultato è una qualità eccezionale in ogni immagine.Fotocamera digitale Mirrorless Sony con sensore APS-C CMOR Exmor 24.3 megapixel.Kit con obiettivo SEL 16-50 mm, Mirino OLED Tru-Finder ad alta risoluzione, Processore di immagini BIONZ X, 179 punti Eye AF, Flash integrato, display 3\" LCD inclinabile 180°, Compatibilità obiettivi: attacco E di Sony',
        'sconto' => 20,
        'marca' => 'Sony',
        'immagine' => '15.jpg',
        'sottocategoria' => 1
        ],
        ['prezzo' => 12499.00,
        'nome' => 'Sony PXW-FS7 ',
        'desc_breve' => 'La videocamera professionale Sony PXW-FS7 Mark II + 18-110mm è un sistema di telecamere 4K ',
        'desc_esaustiva' => 'L\'unità FS7 II è dotata di un sensore CMOS Exmor Super 35mm 4K Single-Chip, che offre immagini con una profondità di campo cinematografica. La fotocamera è dotata di un attacco E che non arrugginisce e offre un potente bloccaggio di tutti gli obiettivi. Potrà essere utilizzato qualsiasi obiettivo con innesto E, tutte le connessioni elettriche sono supportate. I video 4K o UHD fino a 60fps o HD fino a 180fps possono essere archiviati su schede di memoria XQD. È inoltre possibile scegliere di memorizzare le immagini in XVAC-I XVAC-L o MPEG-2. Inoltre, gli slot per schede di memoria two-XQD offrono la possibilità di effettuare registrazioni simultanee o relay. Sensore CMOS Exmor Super 35mm 4K a chip singolo. Videocamera per professionisti 4K (4096 x 2160) e UHD (3840 x 2160) a 60 fps. Video HD fino a 180 fps per super slow motion. Due slot per schede di memoria XQD. Funzionamento comodo ed ergonomico. Filtro ND variabile elettronico incorporato (regolabile tra 2 e 7 stop). 2x uscite HD / 3G-SDI e 1 x uscita HDMI. Registra la videocamera Sony per PrimeSupportPro',
        'sconto' => 20,
        'marca' => 'Sony',
        'immagine' => '16.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' => 3628.00,
        'nome' => 'Canon EOS C100 ',
        'desc_breve' => 'L\'offerta Canon EOS C100 Mark II+EF 18-135mm IS STM unisce le prestazioni della fotocamera compatta',
        'desc_esaustiva' => 'La fotocamera EOS C100 Mark II è una versione aggiornata della tecnologia C100 Dual Pixel CMOS AF che abilita una messa a fuoco continua con obiettivi Canon compatibili. Questo assicura un autofocus più veloce e accurato per aiutare gli utenti quando lavorano con piccoli team. Oltre all\'autofocus Dual Pixel CMOS AF, il Mark II presenta una grande varietà di funzionalità potenziate tra cui il riconoscimento facciale AF, la registrazione MP4, formati extra in ripresa AVCHD, opzioni di ripresa accelerata e al rallentatore in MP4. Il Mark II ha anche un microfono addizionale sul corpo macchina per registrare i suoni quando la maniglia superiore viene rimossa, oltre a uno schermo da 3.5 pollici OLED a risoluzione aumentata; il EVF è ora il doppio dell\'originale ed è inclinabile. Il Mark II supporta il GPS ed ha una funzionalità wireless incorporata. L\'uscita HDMI supporta la funzione time code, come l\'originale C100, oltre alal funzione Canon Log LUT. L\'EOS C100 Mark II utilizza lo stesso sensore Super 35mm Canon CMOS del suo fratello maggiore, il C300, ma ha un processore Digic DV 4. Grazie all\'attacco EF, la macchina è compatibile con l\'intera gamma degli obiettivi EF Canon EF, EF-S e EF Cinema. Questo si rivela paerticolarmente utile per i fotografi DSLR che hanno già investito negli obiettivi Canon. La fotocamera utilizza l\'AVCHD codec per video da 1080p fino a 24 M bps. Sono supportate le schede di memoria dual SD / SDHC / SDXC, che grazie al codec AVCHD consente di registrare almeno tre ore di video HD su ogni scheda da 32 GB. Per le applicazioni professionali, puoi registrare video non compressi 4: 2: 2 con time code incorporato via uscita HDMI.',
        'sconto' => 23,
        'marca' => 'Canon',
        'immagine' => '17.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' => 1199.00,
        'nome' => 'SeaLife DC2000 ',
        'desc_breve' => 'Il set di flash è un pacchetto completo contenente SeaLife DC2000 e un flash Sea Dragon Sea Dragon',
        'desc_esaustiva' => 'La fotocamera è impermeabile fino a 18 metri e con alloggiamento fino a 60 metri. Grazie a un ampio sensore di immagine da 20 megapixel retroilluminato Sony e alla registrazione RAW, il DC2000 offre risultati eccellenti. Quando si riprende sott\'acqua si sa che un buon flash è l\'accessorio più importante per realizzare registrazioni meravigliosamente colorate. Grazie al flash SeaLife SeaDragon i colori di foto e video saranno fantastici. Sensore di immagine da 1 pollice Sony da 20 megapixel per foto e video nitidi. Formati JPEG e RAW. Velocità dell\'otturatore e apertura regolabili manualmente da F1.8 a F11 in 17 fermate. 3 filtri colorati integrati per la correzione del colore digitale subacquea. 4 impostazioni subacquee con correzione del colore integrata. Continuous Burst acquisisce 8 scatti al secondo ad alta risoluzione. La profondità massima è di 60 metri. Wifi per trasferimento wireless e condivisione file',
        'sconto' => '',
        'marca' => 'SeaLife',
        'immagine' => '18.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' => 5749.00,
        'nome' => 'Blackmagic URSA Mini Pro 4.6K G2 ',
        'desc_breve' => 'La Blackmagic è una videocamera digitale di nuova generazione con elettronica aggiornata',
        'desc_esaustiva' => 'La fotocamera offre un sensore super-35mm per 4.6K con una gamma dinamica di 15 fotogrammi, filtri ND ottici integrati e un innesto di cambio EF, che è intercambiabile con montaggi opzionali PL, B4 o F. Include anche RAW e ProRes in Blackmagic e consente la registrazione diretta su unità esterne con la sua innovativa porta di espansione USB-C. Inoltre, URSA Mini Pro 4.6K G2 si distingue per numerosi controlli esterni tipici della trasmissione, un display di stato retroilluminato, un touchscreen pieghevole e altro ancora.LCD da 4 \"con touchscreen capacitivo, dimensioni effettive del sensore: 25,34 mm x 14,25 mm (Super 35), gamma dinamica 15 f-stop, innesto EF con innesto obiettivo incluso (intercambiabile con innesti opzionali PL, B4 e F) . Dettagli tecnici: Dimensioni effettive del sensore: 25,34 mm x 14,25 mm (Super 35) Attacco obiettivo: attacco EF incluso (sostituibile con supporti PL, B4 e F opzionali). Controllo del diaframma: controllo elettronico di obiettivi compatibili attraverso i poli sull\'EF -Monto o porta di trasmissione a 12 pin Gamma dinamica: 15 f-stop. Filtri ND integrati: rotella filtro ND per impostare le quattro posizioni possibili del filtro ND in f-stop: \"Clear\" (nessun filtro), \"2 stop\", \"4 stop\" e \" 6 arresti \". Messa a fuoco: il pulsante di messa a fuoco attiva la funzione di picco (autofocus disponibile su obiettivi compatibili). Controllo del diaframma: rotella del diaframma e cursore del touchscreen per la regolazione manuale dell\'obiettivo controllabile elettronicamente; Pulsante di apertura • Per le impostazioni di apertura automatica istantanea di obiettivi compatibili per evitare pixel ritagliati in modalità \"filmato\". Esposizione automatica basata sul contrasto medio della scena in modalità \"Video\" Dimensioni dello schermo: 4 pollici.>Tipo di schermo: LCD con touchscreen capacitivo. Supporto dei metadati: acquisizione automatica dei dati dell\'obiettivo di obiettivi elettronici EF, B4 e compatibili con tecnologia i / tecnologia; memorizzazione automatica delle impostazioni della fotocamera e dei dati dei file di film come progetto, numero di scena, riprese e note speciali. Controlli: menu touchscreen su schermo da 4 pollici. Pulsanti per funzioni aggiuntive; 2 tasti di scelta rapida assegnabili. Generatore di codice temporale: generatore di codice temporale ad alta precisione, la deviazione di temporizzazione ogni 8 ore è inferiore a un fotogramma',
        'sconto' => '',
        'marca' => 'Blackmagic',
        'immagine' => '19.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' => 2649,
        'nome' => 'CANON LEGRIA GX10 ',
        'desc_breve' => 'Filmati 4K straordinari anche senza treppiede e controllo creativo di livello professionale',
        'desc_esaustiva' => 'Crea storie d\'incredibile qualità 4K: Questa videocamera 4K 50p è dotata di messa a fuoco Dual Pixel CMOS AF, slow motion a 100 fps in Full HD, Wide DR e due slot per schede di memoria per creare storie di qualità professionale. Riprendi in formato 4K: riprendi filmati in 4K a 50p incredibilmente vivaci con la funzione Wide DR, anche nelle situazioni più difficili, grazie alle ottiche di precisione, allo zoom da 15x, all\'ampio sensore e al filtro ND da 8 stop. Qualità professionale: riprendi a mano libera in modo semplice grazie alla leva zoom professionale, alla ghiera dell\'obiettivo, all\'ampio touch screen orientabile con messa a fuoco Dual Pixel CMOS AF e alla potente stabilizzazione dell\'immagine. Controlli semplici e personalizzabili: prendi il controllo grazie ai pulsanti e alle ghiere facilmente personalizzabili e al telecomando wireless incluso oppure ottieni immediatamente eccezionali risultati in 4K con la modalità automatica. Cattura l\'azione: riprendi filmati in 4K a 50p, per fluidità e realismo straordinari. Crea fantastici slow motion a 50 fps in 4K e fino a 100 fps in Full HD. Sfrutta la registrazione continua su due schede di memoria per sessioni prolungate e backup.Semplice flusso di lavoro, elevata qualità audio: condividi contenuti via wireless e riprendi da remoto utilizzando il tuo dispositivo smart con Wi-Fi dual band. Aggiungi audio di alta qualità grazie all\'ingresso audio da 3,5 mm e alla mini slitta avanzata Canon.',
        'sconto' => '',
        'marca' => 'Canon',
        'immagine' => '20.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' => 1099.90,
        'nome' => 'Blackmagic Micro Cinema ',
        'desc_breve' => 'La più piccola cinepresa digitale al mondo con telecomando innovativo, una cinepresa digitale',
        'desc_esaustiva' => 'Usa il telecomando integrato per catturare azioni ovunque. Uno slot di modulo integrato rivoluzionario, chiamato porta di espansione, ha ingressi PWM e S.BUS, consentendo l\'utilizzo di un telecomando per aeromodelli e di un controllo wireless della telecamera. Difficile da immaginare: la regolazione wireless di messa a fuoco, apertura e zoom. La Micro Cinema Camera è una vera videocamera digitale che registra in RAW e ProRes. Trionfa con una gamma dinamica di 13 f-stop e un innesto obiettivo MFT. Come una vera macchina da presa digitale, viene utilizzata dove altre macchine da presa digitali non possono competere!. Realizza scatti d\'azione sensazionali. La Blackmagic Micro Cinema Camera è una fotocamera digitale incredibilmente piccola e di classe professionale, perfetta per l\'uso su quadrocopter, come crash cam o come telecamera nascosta sul set per i reality show. Può essere montato praticamente ovunque, compresi skateboard o alianti per riprese di sport estremi o un drone per creare scatti di pan-bird da una vista dall\'alto. O fissa la fotocamera su un casco per creare fantastici scatti POV! Il tuo pubblico sarà colpito dalla Blackmagic Micro Cinema Camera ed esclamerà: \"Wow, come è nata questa ripresa?\". Sensore Super 16mm La risoluzione Full 1080 full HD a 16 sensori della fotocamera Blackmagic Micro Cinema ha un\'incredibile gamma dinamica di 13 frame. D. h. Ottieni registrazioni con la vera qualità di un film digitale, perché il sensore acquisisce più informazioni nelle aree chiare e scure delle registrazioni. La DSLR e le action cam sono limitate ai contenuti video che tagliano luci e ombre. La Blackmagic Micro Cinema Camera, d\'altra parte, ti dà luci più luminose, senza toni di ritaglio, e i più piccoli dettagli nelle ombre. Con un valore ISO fino a 1600, ottieni la migliore qualità dell\'immagine anche in ambienti a bassa esposizione.Registratore RAW e ProRes integrato Il registratore incorporato registra in modalità di registro a 12 bit reale nella qualità di film digitale reale senza il rumore tipico dei file H.264 a 8 bit altamente compressi su azioni di piccole dimensioni e DSLR Le telecamere si verificano. I file possono essere salvati nei formati Cinema DNG RAW o ProRes. I file Cinema DNG RAW funzionano in modalità registro a 12 bit e forniscono tutti i dati acquisiti dal sensore della videocamera, il che significa che hai la libertà di modificare impostazioni come il bilanciamento del bianco e l\'esposizione molto dopo la fine della registrazione. Se hai bisogno di file più piccoli e durate di registrazione più lunghe, puoi lavorare con ProRes in qualità di trasmissione. Entrambi i formati possono essere comodamente tagliati e corretti per colore in DaVinci Resolve,incluso per Mac e Windows.',
        'sconto' => 20,
        'marca' => 'Blackmagic',
        'immagine' => '21.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' => 1379.00,
        'nome' => 'Blackmagic Pocket Cinema 4K MFT ',
        'desc_breve' => 'La videocamera Blackmagic Pocket Cinema 4K MFT ha sensore 4/3, gamma dinamica di 13 stop',
        'desc_esaustiva' => 'I comandi esterni ti danno immediato accesso a funzioni chiave, mentre il topuchscreen da 5 pollici rende facile la messa a fuoco, le operazioni di crop e la regolazione della videocamera. Le caratteristiche includono un registratore incorporato per SD/UHS-II o una scheda CFast 2.0 per registrazioni RAW o ProRes e un\'espansione USB-C per la registrazione su supporto di memoria esterno. La macchina è dotata di attacco micro quattro terzi, microfoni incorporati, connettore mini-XLR, una porta HDMI, supporto 3D LUT, Bluetooth e altre funzionalità. Videocamera Pocket Cinema 4K. Professionale, portabile e dal prezzo accessibile. Touchscreen da 12.7 cm (5 pollici). ISO fino a 25,600. Attacco micro quattro terzi con contorllo elettronico dell\'iride. Prestazioni eccellenti anche con poca luce',
        'sconto' => 50,
        'marca' => 'Blackmagic',
        'immagine' => '22.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' => 1969.00,
        'nome' => 'JVC GY-HM250E ',
        'desc_breve' => 'Con la videocamera Ultra HD Streaming 4K di JVC GY-HM250E puoi registrare 4K Ultra HD',
        'desc_esaustiva' => 'L\'obiettivo zoom 12x integrato e il sensore 4K CMOS offrono immagini Ultra HD nitide che possono essere registrate direttamente su schede di memoria SDHC / SDXC. Allo stesso tempo, il camcorder ha una tecnologia di streaming dual codec avanzata. Questa fotocamera ha anche una modalità teleobiettivo per ottenere oggetti nitidi a distanza ravvicinata e può visualizzare titoli grafici sia nella parte inferiore dello schermo che nell\'intera immagine. Sensore CMOS singolo da 1 / 2,3 pollici con 12,4 milioni di pixel (9,03 attivi). Zoom dinamico in modalità HD, combina lo zoom ottico e la mappatura dei pixel per creare uno zoom 24x continuo senza perdita di qualità. Registrazione 4: 2: 2 in full HD a 50 Mbps (24-60p). Registrazione HD a rallentatore 120fps. Uscita video UHD 4K in diretta, tramite HDMI. Filtro ND con 2 posizioni (1/4, 1/16). Uscite HD-SDI (3G) e HDMI (solo 4K da HDMI). 2x slot SDHC / SDXC per doppia,backup e registrazione continua. Avanzata tecnologia di streaming JVC, compatibile con la tecnologia di streaming USTREAM, Zixi e Wowza. Controllo remoto tramite rete (IP), visualizzazione remota, elaborazione dei metadati, upload di clip FTP (richiesta connessione e adattatore di rete corretti). Microfono stereo incorporato. Display LCD a colori da 3,5 pollici (920K pixel) con funzione di assistenza alla messa a fuoco intelligente. Mirino a colori da 0,24 pollici (1,56 M pixel) con funzione di assistenza alla messa a fuoco intelligente. Supporto per un telecomando cablato. 9 pulsanti utente programmabili. Include la sezione maniglia e la batteria SSL-JVC50 da 7,4 V, adattatore CA. Funzioni di trasmissione. Sovrapposizioni grafiche personalizzabili (on / off). Opzione per i loghi, la filigrana, il tempo e la temperatura personalizzati dell\'emettitore. Loghi precaricati selezionabili. Obiettivo zoom 12x F1.2-3.5 integrato. (equivalente 35 mm: 29.5354 mm). Scheda Ultra HD 4K (150 Mbps, 24 / 30p) su scheda SDXC (UHS-I Speed ​​Class 3). Microfono esterno e Wi-Fi o LTE Dongle non inclusi',
        'sconto' => '',
        'marca' => 'JVC',
        'immagine' => '23.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' => 2.247,
        'nome' => 'PANASONIC AG-UX180 ',
        'desc_breve' => 'La videocamera è dotaata di funzioni e specifiche professionali per operatori esperti.',
        'desc_esaustiva' => 'Il camcorder supporta la registrazione multiformato in 4K a 24p, UHD a 60p/50p, FHD a 60p/50p e la modalità Super Slow-Motion HD. Due slot per schede di memoria SD*1 consentono la registrazione relay/simultanea/di riserva, per un\'affidabilità superiore, mentre la possibilità di registrare a doppio codec UHD/FHD assicura un flusso di lavoro più efficiente.I comandi dell\'AG-UX180, come ad esempio le tre ghiere manuali e il pulsante dell\'utente, nonché le interfacce, quali gli ingressi 3G-SDI/HDMI e XLR, sono stati progettati per soddisfare le esigenze della videoregistrazione professionale. Con lo stesso livello di agilità e mobilità di un camcorder palmare HD tradizionale, l\'AG-UX180 supporta efficacemente la produzione di video in 4K a un\'elevata qualità dell\'immagine.Il grandangolo più ampio del settore (24 mm)*2 e l\'obiettivo con zoom ottico 20x di nuova concezione. Il primo*3 zoom ottico 20x al mondo in un camcorder con sensore da 1\"*4: l\'obiettivo con zoom ottico da 20x copre la gamma da 24 mm, all\'estremità del grandangolo, fino a 480 mm, all\'estremità telescopica (equivalente a pellicola da 35 mm in 4K a 24p).Sistema di obiettivi 4-Drive: gestisce simultaneamente e in modo indipendente 4 gruppi ottici (gruppo 2, diaframma, gruppo 3, gruppo 4) Le dimensioni dell\'obiettivo e l\'intervallo di azionamento di ciascuno dei 4 gruppi si possono ridurre con efficienza per ottimizzare la qualità dell\'immagine e la potenza dello zoom, garantendo allo stesso tempo un corpo compatto.Il grandangolo più ampio del settore, con 24 mm*5: l\'obiettivo integrato vanta il grandangolo più ampio del settore (24 mm) nell\'impostazione grandangolare. Questa caratteristica consente di effettuare riprese panoramiche con la minima distorsione, senza dover ricorrere a obiettivi di conversione, e inoltre di registrare/produrre video su veicoli o in interni, ad esempio. Zoom intelligente per ingrandimenti massimi di 30x a risoluzione super-elevata: nelle modalità di ripresa FHD, la funzione i.Zoom aumenta la capacità dello zoom fino a circa 30x, pur mantenendo una risoluzione elevata. Quando raggiunge il limite di 20x dello zoom ottico, il camcorder passa direttamente a i.Zoom.Zoom digitale (2x, 5x o 10x): l\'AG-UX180 offre uno zoom digitale da 2x, 5x e 10x. Se si utilizza lo zoom ottico 20x in combinazione con i.Zoom, si ottiene un ingrandimento da superteleobiettivo fino a 300x, senza perdite di intensità luminosa. Obiettivo LEICA DICOMAR*6: questo obiettivo ha superato i rigorosi standard qualitativi di Leica Camera AG. Un processo di rivestimento multiplo riduce al minimo gli effetti ghost e flare, creando immagini di estrema nitidezza.',
        'sconto' => '',
        'marca' => 'Panasonic',
        'immagine' => '24.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' => 1559.99,
        'nome' => 'PANASONIC AG-AC30',
        'desc_breve' => 'La AG-AC30 è una videocamera palmare con eccellenti caratteristiche',
        'desc_esaustiva' => 'La sua luce video a LED con 2 filtri di luce incluso permette di tiro affidabile anche nelle scene notturne e luoghi oscuri come il filtro di conversione colore adatta la temperatura di colore, mentre il filtro diffusore ammorbidisce la fonte di luce. Le caratteristiche di scarsa illuminazione in circolazione della videocamera è il risultato del sensore BSI 1 / 3.1-tipo built-in, di nuova concezione, che raggiunge una elevata qualità delle immagini di 6.03M pixel effettivi. Ciò consente luminose, belle inquadrature anche in luoghi bui. Modello: AG-AC30. Dimensioni schermo: 3 pollici. Dispone di stabilizzatore di immagini: Sì. Zoom ottico: 20 X. Touch Panel: 460K puntini 3.0 di tipo LCD. Cam remoto: Focus IRIS & Zoom S / S. Risoluzione sensore ottico: 6.03 MP. Risoluzione immagine: 1920 x 1080 Full HD. Risoluzione Video: 1920 x 1080 Full HD. Live Video Frame Rate: 60/100 fps. Display LCD. Tipo di sensore: 1 / 3.1-tipo BSI sensore MOS. Connettività: HDMI / USB 2.0 / XLR Analog Mic / Line Switchable (Phantom Power) . Tipo di Storage: SDHC / SDXC. Formati immagini supportati: DCF / EXIF / JPEG. Formati video supportati: AVCHD / MOV / MPEG-4. Colore Nero. Dimensioni prodotto: 170 x 170 x 335 mm.',
        'sconto' => 12,
        'marca' => 'Panasonic',
        'immagine' => '25.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' =>26,
        'nome' => 'SONY PXW-FS5 ',
        'desc_breve' => 'Super35 CMOS Sensor, 3840 x 2160p Video, 100BASE-TX/10BASE-T LAN',
        'desc_esaustiva' => 'Se usi un camcorder portatile, dovresti poterti muovere ovunque. Lavorare da seduto. Seguire il set. Effettuare riprese da angolazioni insolite con eguale agilità. In più, una telecamera portatile deve funzionare perfettamente anche appoggiata al torace, o tenuta ferma senza difficoltà con la mano destra, con tutti i comandi a portata di mano. La straordinaria PXW-FS5 di Sony è tutto questo e molto altro. L\'FS5 è una rivisitazione radicale dell\'FS7, e offre riprese in movimento senza precedenti nelle condizioni più difficili. Grazie a un corpo che pesa meno della metà della FS7 (0,8 kg), puoi riprendere praticamente ovunque. Il funzionamento a mano è semplicemente eccezionale, dato che lo chassis bilanciato può essere configurato con semplicità ad angolazioni alte e basse, grazie all\'impugnatura flessibile e rotante e al viewfinder LCD, che può essere montato in nove diverse posizioni. E come avviene spesso con i prodotti di Sony, per fornire un controllo completo sull\'illuminazione nelle situazioni in rapido movimento, abbiamo inventato il primo filtro ND elettronico variabile per un camcorder Super 35 mm. Quando sei sul campo, è importante cogliere subito ogni opportunità, non c\'è tempo da perdere. L\'FS5 consente di aggiungere o rimuovere rapidamente i componenti come l\'impugnatura e il viewfinder LCD senza strumenti speciali, mentre i fori per le viti da 1/4\" supportano il montaggio su un drone, un supporto gimbal o in una custodia subacquea. Il sistema α-Mount di Sony offre una compatibilità insuperabile sia con le ottiche di Sony che di terzi. L\'E-Mount della FS5 è compatibile con gli obiettivi cinematografici ed SLR grazie all\'uso di un adattatore di terze parti, oltre che con le ottiche E-Mount e A-Mount di Sony, per semplificare al massimo l\'utilizzo di ottiche nuove o acquistate precedentemente. Quando la qualità è prioritaria, sfrutta appieno il sensore Exmor della FS5 Super 35 e riprendi in 4K a 100 Mbps (3840 x 2160), avvalendoti del sistema di registrazione XAVC avanzato (Long GOP) di Sony. In futuro sarà disponibile un\'opzione per registrare esternamente file RAW (dettagli ancora da annunciare). Se invece ciò che cerchi è la rapidità, passa alle riprese Full HD (1920 x 1080) in formato XAVC fino a 60p 10 bit 4:2:2 a 50 Mbps. L\'FS5 ha la flessibilità di adattarsi al modo in cui desideri lavorare, oggi come domani. Le riprese in High Frame Rate possono trasformare l\'azione di ogni giorno in una danza in slow motion, e l\'FS5 è in grado di offrire l\'incredibile frame rate di 240 fps in Full HD XAVC 10 bit 4:2:2. Se il progetto si avvale di un frame rate cinematografico di 24p, puoi utilizzare la bellissima funzione super slow motion 10x. Non è necessario scendere a compromessi in termini di bit di profondità e non si crea l\'indesiderato effetto di \"windowing\" del sensore, pertanto non sono visibili ritagli né perdite nell\'angolazione.',
        'sconto' =>'',
        'marca' => 'Sony',
        'immagine' => '26.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' =>1669,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '27.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '28.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '29.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '30.jpg',
        'sottocategoria' => 2
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '31.jpg',
        'sottocategoria' =>
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '32.jpg',
        'sottocategoria' =>
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '33.jpg',
        'sottocategoria' =>
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '34.jpg',
        'sottocategoria' =>
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '35.jpg',
        'sottocategoria' =>
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '36.jpg',
        'sottocategoria' =>
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '37.jpg',
        'sottocategoria' =>
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '38.jpg',
        'sottocategoria' =>
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '39.jpg',
        'sottocategoria' =>
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '40.jpg',
        'sottocategoria' =>
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '41.jpg',
        'sottocategoria' =>
        ],
        ['prezzo' =>,
        'nome' => ' ',
        'desc_breve' => '',
        'desc_esaustiva' => '',
        'sconto' =>,
        'marca' => '',
        'immagine' => '42.jpg',
        'sottocategoria' =>
        ],
    }

}
