<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder {

    /**
     * Seed the application's database.
     *
     * @return void
     */
    // const DESCPROD = '<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem. Phasellus pellentesque. Mauris quam enim, molestie in, rhoncus ut, lobortis a, est. </p><p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc, ut consectetuer nisl felis ac diam. Etiam non felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem. Phasellus pellentesque. Mauris quam enim, molestie in, rhoncus ut, lobortis a, est.</p>';

    public function run() {

        DB::table('categoria')->insert([
            ['nome' => 'Computer'],
            ['nome' => 'Display'],
            ['nome' => 'Dispositivi Mobile'],
            ['nome' => 'Foto e Video'],
        ]);
        DB::table('sottocategoria')->insert([
            ['nome' => 'Fotocamere', 'categoria' => 'Foto e Video'],
            ['nome' => 'Videocamere', 'categoria' => 'Foto e Video'],
            ['nome' => 'Action cam', 'categoria' => 'Foto e Video'],
            ['nome' => 'Treppiedi', 'categoria' => 'Foto e Video'],
            ['nome' => 'Tablet', 'categoria' => 'Dispositivi Mobile'],
            ['nome' => 'Smartphone', 'categoria' => 'Dispositivi Mobile'],
            ['nome' => 'Laptop', 'categoria' => 'Computer'],
            ['nome' => 'Desktop', 'categoria' => 'Computer'],
            ['nome' => 'TV', 'categoria' => 'Display'],
            ['nome' => 'Monitor', 'categoria' => 'Display'],
        ]);
        DB::table('prodotto')->insert([
            ['prezzo' => 470.00,
                'nome' => 'Nikon D3500',
                'desc_breve' => 'Nikon D3500 Fotocamera Reflex Digitale con Obiettivo Nikkor AF-P 18-55, F/3.5-5.6G VR DX',
                'desc_esaustiva' => 'Nikon D3500: fotografa, riprendi video, condividi, divertiti, stupisci. La nuova reflex digitale \"entry level\" da 24,2 Megapixel è la fotocamera perfetta per chi si avvicina al mondo della fotografia, in virtù del suo design confortevole e delle sue modalità di ripresa che ne rendono facilissimo l\'uso. In più, con Nikon SnapBridge condividere immediatamente le immagini straordinarie che vengono realizzate è facilissimo: impossibile non farlo. Versatile kit con obiettivo zoom per eccezionali fotografie di tutti i giorni. Include la fotocamera D3500, nonché il compatto obiettivo con zoom AF-P DX NIKKOR 18–55mm VR. L\'obiettivo di questo kit assicura una veloce e fluida messa a fuoco, ideale per le riprese di filmati con la quasi totale eliminazione del disturbo meccanico. Lo straordinario sistema di riduzione vibrazioni di Nikon garantisce la nitidezza delle foto anche in condizioni di scarsa illuminazione.',
                'sconto' => 10,
                'marca' => 'Nikon',
                'immagine' => '1.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 429.00,
                'nome' => 'Nikon D3300',
                'desc_breve' => 'Nikon D3500 Fotocamera Reflex Digitale con Obiettivo Nikkor AF-P 18-55, F/3.5-5.6G VR DX',
                'desc_esaustiva' => 'Catturate la vera atmosfera dei momenti importanti con la fotocamera D3300 Potente, comoda da trasportare e di facilissimo utilizzo, questa D-SLR da 24.2 megapixel, piccola e leggera, è un ottimo modo per riprendere indimenticabili foto e filmati ad alta definizione.Il Modo guida fornisce assistenza passo-passo a coloro che si avvicinano per la prima volta alla fotografia D-SLR o a chi desidera ulteriori informazioni, utilizzando immagini di esempio e istruzioni chiare per mostrarvi come scattare foto e riprendere filmati fantastici.Per chi vuole condividere, l\'adattatore wireless per la comunicazione con dispositivi mobili di Nikon semplifica il caricamento di foto nei siti preferiti tramite uno smart device.Riprendete immagini chiare con qualsiasi tipo di luce. Il processore di elaborazione delle immagini di Nikon, rapido e potente, garantisce un funzionamento veloce e funzioni avanzate di riduzione disturbo, per ottenere immagini estremamente nitide con colori naturali in qualsiasi condizione di illuminazione.È possibile riprendere le azioni alla rapida cadenza di 5 fotogrammi al secondo e catturare movimenti ed espressioni fugaci esattamente al momento giusto.Obiettivo zoom in formato DX compatto e leggero per eccezionali scatti di vita quotidiana. Con una portata dello zoom da grandangolare a normale e una struttura compatta, è l\'obiettivo ideale per scattare tra la gente. È sempre pronto a mettere a fuoco una grande varietà di soggetti, da scatti urbani ai paesaggi fino a eventi sportivi e a filmati HD pieni d\'azione. Qualunque sia il soggetto, il sistema di riduzione vibrazioni di Nikon garantisce la nitidezza delle immagini anche in condizioni di scarsa illuminazione. Il design snello dell\'obiettivo assicura compattezza e comodità di trasporto.',
                'sconto' => '',
                'marca' => 'Nikon',
                'immagine' => '2.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 334.99,
                'nome' => 'Nikon Coolpix B500',
                'desc_breve' => 'Nikon Coolpix B500 Fotocamera Digitale Compatta, 16 Megapixel, Zoom 40X, ISO 125 - 6.400, VR, LCD',
                'desc_esaustiva' => 'Esplorate la potenza dello zoom ottico NIKKOR 40x, estendibile a Dynamic Fine Zoom¹ 80x, mettendovi al centro dell\'azione, con il controllo zoom laterale che assicura una superba stabilità. Scattate foto da un punto di vista esclusivo con il monitor LCD inclinabile ad alta definizione, catturate di nuovo i soggetti con facilità con il pulsante ripristina posizione zoom e mantenete connessa la fotocamera allo smart device con SnapBridge. Il funzionamento intuitivo semplifica le riprese e le funzioni utilizzate di frequente sono accessibili dalla ghiera di selezione modo, mentre il design classico assicura la maneggevolezza necessaria. La COOLPIX B500 da 16 megapixel consente di catturare i momenti della vita da una prospettiva creativa. ZOOM OTTICO NIKKOR 40X Catturate tutta l\'azione degli eventi sportivi, riprendete soggetti distanti con nitidi dettagli in ambientazioni urbane o scattate immagini incredibilmente nitide della luna o del cielo notturno con l\'obiettivo zoom ottico NIKKOR 40x, estendibile a Dynamic Fine Zoom¹ 80x. Le affidabili ottiche NIKKOR garantiscono prestazioni eccezionali e potrete utilizzare un potente obiettivo con angoli di campo dalla copertura grandangolare di 22,5 mm al super teleobiettivo da 900 mm (equivalente alle lunghezze focali nel formato 35 mm) in una fotocamera compatta.',
                'sconto' => '',
                'marca' => 'Nikon',
                'immagine' => '3.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 584.39,
                'nome' => 'Nikon Coolpix P900',
                'desc_breve' => 'Nikon Coolpix P900 Fotocamera Digitale Compatta, Sensore CMOS 16 Megapixel, Zoom 83X, VR, LCD 3", Full HD, Wi-Fi, GPS, GLONASS, QZSS, Nero [Nital Card: 4 Anni di Garanzia]',
                'desc_esaustiva' => 'L\'incredibile zoom ottico 83x della COOLPIX P900 a 16 megapixel consente ai fotografi appassionati di riprese naturalistiche o di cieli notturni di catturare dettagli non visibili a occhio nudo. Eseguite riprese istantanee con AF rapido e un ritardo allo scatto inferiore, mentre il sistema VR ottico a doppio rilevamento con un tempo di posa di 5,0 stop riduce ulteriormente l\'effetto mosso. Composizioni flessibili con il monitor ad angolazione variabile e il mirino elettronico incorporato per riprendere immagini fisse dettagliate con il super teleobiettivo e filmati Full HD. Il supporto GPS/GLONASS/QZSS incorporato localizza le posizioni di scatto e le immagini possono essere condivise immediatamente grazie al Wi-Fi¹ integrato e al supporto NFC². La COOLPIX P900, dal design modellato per garantire riprese agevoli, vi avvicina più che mai alla bellezza della natura.',
                'sconto' => '',
                'marca' => 'Nikon',
                'immagine' => '4.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 482.5,
                'nome' => 'Nikon Coolpix B500 ',
                'desc_breve' => 'Nikon Coolpix B500 Fotocamera Digitale Bridge, 16 Megapixel, Zoom 83X, VR, LCD 3", Full HD, Wi-Fi ',
                'desc_esaustiva' => 'Meravigliosa qualità dell\'immagine con semplicità grazie alla Nikon COOLPIX B500. Esplorate la potenza dello zoom ottico NIKKOR 40x, estendibile a Dynamic Fine Zoom¹ 80x, mettendovi al centro dell\'azione, con il controllo zoom laterale che assicura una superba stabilità. Scattate foto da un punto di vista esclusivo con il monitor LCD inclinabile ad alta definizione, catturate di nuovo i soggetti con facilità con il pulsante ripristina posizione zoom e mantenete connessa la fotocamera allo smart device con SnapBridge. Il funzionamento intuitivo semplifica le riprese e le funzioni utilizzate di frequente sono accessibili dalla ghiera di selezione modo, mentre il design classico assicura la maneggevolezza necessaria. La COOLPIX B500 da 16 megapixel consente di catturare i momenti della vita da una prospettiva creativa.',
                'sconto' => 20,
                'marca' => 'Nikon',
                'immagine' => '5.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 339.99,
                'nome' => 'Canon EOS 2000D ',
                'desc_breve' => 'Canon EOS 2000D + EF-S 18 - 55 mm IS II Fotocamera Reflex, Sensore APS-C da 24.1 megapixel',
                'desc_esaustiva' => 'Crea foto di qualità reflex ricche di dettagli e filmati Full HD cinematografici in tutta semplicità e anche in condizioni di scarsa illuminazione, con EOS 2000D da 24.1 megapixel. Passa a un sensore da 24.1 megapixel che dispone di una superficie fino a 19 volte maggiore rispetto a quella di molti smartphone. Esegui scatti guidati in Live View grazie alla modalità creativa automatica e aggiungi finiture uniche con i filtri creativi. Trasforma i momenti più spontanei in filmati Full HD creativi oppure utilizza la modalità Video Snapshot per catturare i momenti più importanti della tua giornata. Corpo Eos 2000D, Oculare Mirino, Tracolla per Fotocamera Ew-400D, Batteria Lp-E10, Caricabatteria Lc-E10E, Cavo di Alimentazione per Carica Batteria',
                'sconto' => 35,
                'marca' => 'Nikon',
                'immagine' => '6.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 328.00,
                'nome' => 'Canon Italia EOS 4000D ',
                'desc_breve' => 'Canon Italia EOS 4000D + EF-S DC III Fotocamera Reflex, Nero, Lunghezza Focale 18-55 mm',
                'desc_esaustiva' => 'Creare storie uniche con foto di qualità reflex e filmati in Full HD è più semplice di quanto credi con la fotocamera EOS 4000D da 18 megapixel. Scatta immagini splendide con sfondo naturale sfocato in tutta semplicità. Trasforma i momenti di ispirazione in filmati Full HD creativi oppure utilizza la modalità Video Snapshot. Trasferisci istantaneamente foto e filmati sul dispositivo smart per condividerli facilmente sui social media o eseguire il backup sul servizio cloud irista. Corpo Eos 4000D, Oculare Mirino, Tracolla per Fotocamera Ew-400D, Batteria Lp-E10, Caricabatteria Lc-E10E, Cavo di Alimentazione per Carica Batteria',
                'sconto' => 22,
                'marca' => 'Canon',
                'immagine' => '7.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 362.05,
                'nome' => 'Canon Italia PowerShot SX740 ',
                'desc_breve' => 'Canon Italia PowerShot SX740 Fotocamera Digitale Compatta, Nero',
                'desc_esaustiva' => 'L\'esclusivo processore Canon DIGIC 8 gestisce attivamente le impostazioni della fotocamera come Zoom Framing Assist e Hybrid Auto, consentendoti di inquadrare e scattare con risultati incredibili. La spettacolare risoluzione 4K per i filmati e la stabilizzazione a 5 assi consentono di catturare i momenti più belli con dettagli incredibili, anche quando sei in movimento. Non perderti nemmeno un istante grazie alla risposta incredibilmente rapida dell\'otturatore e allo scatto continuo fino a 10 fps. Il Bluetooth, la connessione Wi-Fi e il trasferimento automatico avanzati ti permettono di condividere e archiviare facilmente le foto sul PC di casa o su dispositivi compatibili. Fotocamera digitale PowerShot SX740 HS (BK), cinturino da polso WS-800, batteria NB-13L, carica batteria CB-2LHE, cavo CA (E), kit manuale dell\'utente',
                'sconto' => 13,
                'marca' => 'Canon',
                'immagine' => '8.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 282.13,
                'nome' => 'Canon EOS 1300D ',
                'desc_breve' => 'Canon EOS 1300D Kit Fotocamera Reflex Digitale da 18 Megapixel con Obiettivo EF-S IS II 18-55 mm',
                'desc_esaustiva' => 'Ottieni immagini ricche di dettaglio grazie a un ampio sensore in formato APS-C da 18 megapixel. Stampa le tue immagini fino al formato A2 oppure ritagliale in modo creativo per ottenere risultati di qualità. Scatta foto memorabili anche in condizioni di bassa luce grazie all\'ampia gamma di sensibilità ISO 100-6400 (espandibile fino a ISO 12.800) che ti consente di ridurre la necessità di ricorrere al flash per catturare la vera atmosfera di ogni prezioso ricordo. Con la fotocamera EOS 1300D da 18 megapixel acquisisci facilmente foto di qualità reflex e filmati in Full HD in stile cinematografico. Crea ottimi ritratti che mettono in risalto i tuoi soggetti su sfondi leggermente sfocati grazie alla profondità di campo ridotta tipica della fotografia DSLR. Scatta foto con dettagli, colori e contrasto proprio come li ricordi, grazie al processore DIGIC 4+. Con la tecnologia NFC (Near Field Communication) è possibile collegarsi velocemente a smartphone e tablet Android compatibili e avviare l\'applicazione Camera Connect con un solo tocco. È inoltre possibile collegarsi a dispositivi iOS e non-NFC e avviare l\'applicazione tramite Wi-Fi. Ottimo per un trasferimento rapido e per condividere immagini e filmati in movimento. Trasferisci, memorizza e guarda le tue foto e i tuoi filmati su Canon Connect Station CS100, per una condivisione semplice su un HDTV o su social media e servizi fotografici online come irista.',
                'sconto' => '',
                'marca' => 'Canon',
                'immagine' => '9.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 347.59,
                'nome' => 'Canon EOS 750D  ',
                'desc_breve' => 'Canon EOS 750D Fotocamera Reflex Digitale da 24 Megapixel, Nero/Antracite',
                'desc_esaustiva' => 'Ottieni degli scatti straordinari in qualsiasi situazione grazie al sensore APS-C da 24,2 megapixel e al processore DIGIC 6.. Riprendi facilmente filmati in Full HD di qualità cinematografica con Hybrid CMOS AF III; segue i movimenti e la messa a fuoco tra i soggetti con la massima fluidità.Porta le tue immagini a un livello superiore grazie alla tecnologia reflex di nuova generazione e alla modalità Scena Smart Auto. Condividi i tuoi file online o trasferisci all\'istante le immagini sul tuo dispositivo smart o su Canon Connect Station tramite NFC e Wi-Fi.Contenuto della confezione: Corpo EOS 750D, Oculare mirino, Tappo per fotocamera R-F-3, Tracolla EW-300D, Batteria LP-E17, Sportello del vano batteria, Carica batteria LC-E17, Cavo di alimentazione per carica batteria, Cavo interfaccia IFC-130U, Kit manuale di istruzioni',
                'sconto' => '',
                'marca' => 'Canon',
                'immagine' => '10.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 778.95,
                'nome' => 'Sony Alpha 6300 ',
                'desc_breve' => 'Sony Alpha 6300 Kit Fotocamera Digitale Mirrorless Compatta con Obiettivo Intercambiabile ',
                'desc_esaustiva' => 'Fotocamera compatta con ottiche intercambiabili, sensore Exmor APS-C CMOS da 24.2 MP, processore BIONZ X, ISO 100-51200, mirino XGA OLED 100% copertura (visualizzazione anche a 120fps), Fast hybrid AF (425 punti a rilevamento di fase + 169 a contrasto), 11 fps con AF e 8fps con ritardo ridottissimo di visualizzazione nel mirino/schermo, video 4K interno fino a 30p e Full HD fino a 120p, formato XAVC-S, picture profile, S-log3, S-Gamut 3, corpo in magnesio resistente a polvere e umidità, schermo LCD 3\'\' da 921k punti e whitemagic, wi-fi, NFC, Playmemories Camera Apps, slitta multi-interfaccia, flash integrato, Triluminos Color, Uscita 4K per le foto, batteria NPFW50. Colore nero. Obiettivo SELP1650 F3.5-5.6 OSS.',
                'sconto' => '',
                'marca' => 'Sony',
                'immagine' => '11.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 975.90,
                'nome' => 'Sony Alpha 6400L ',
                'desc_breve' => 'Sony Alpha 6400L Kit Fotocamera Digitale Mirrorless con Obiettivo Intercambiabile SELP 16-50 mm',
                'desc_esaustiva' => 'L\'af più veloce al mondo1 (0,02 sec) combina il meglio dell\'af a rilevamento di fase (425 punti) e a rilevamento di contrasto (425 punti); i punti di messa a fuoco densamente distribuiti coprono l\'84% dell\'area. 1 tra le fotococamere con ottica intercambiabile e sensore aps-c secondo una ricerca sony aggiornata al gennaio 2019. Real-time eye af e real-time tracking grazie alla tecnologia ai di riconoscimento dei soggetti Scatto continuo fino a 11 fps (o 8 fps in silent mode) con af/ae Sensore aps-c exmor cmos da 24.2mp e processore bionz x di ultima generazione. La fotocamera ideale per vloggers e content creators con registrazione video in 4k hdr, fast hybrid af e schermo LCD touch e inclinabile di 180° verso l\'alto (e 74° verso il basso)',
                'sconto' => '',
                'marca' => 'Sony',
                'immagine' => '12.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 990.00,
                'nome' => 'Sony Alpha 6500B ',
                'desc_breve' => 'Sony Alpha 6500B Fotocamera Digitale Mirrorless APS-C ad Obiettivi Intercambiabili',
                'desc_esaustiva' => 'Fotocamera compatta con ottiche intercambiabili, sensore Exmor APS-C CMOS da 24.2 MP, processore BIONZ X e chip d\'acquisizione LSI, stabilizzatore d\'immagine integrato a 5 assi, ISO 100-51200, mirino XGA OLED 100% copertura, Fast hybrid AF (425 punti a rilevamento di fase + 169 a contrasto), velocità di scatto a 11 fps con AF e 8fps con ritardo ridotto di visualizzazione nel mirino/schermo, ampio buffer e scatto continuo fino a 307 scatti, video 4K interno fino a 30p e Full HD fino a 120p, formato XAVC-S, picture profile, S-log3, S-Gamut 3, funzione SlowQuick Motion, corpo in magnesio resistente a polvere e umidità, schermo LCD 3\'\' da 921k punti con funzione touch, Wi-Fi, NFC, compatibilità QR code, Camera Apps, slitta multi-interfaccia, flash integrato, batteria NPFW50. Colore nero.',
                'sconto' => 15,
                'marca' => 'Sony',
                'immagine' => '13.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 899.00,
                'nome' => 'Sony Alpha 7M2K ',
                'desc_breve' => 'Sony Alpha 7M2K Kit Fotocamera Digitale Mirrorless con Obiettivo Intercambiabile SEL 28-70mm',
                'desc_esaustiva' => 'Fotocamera digitale Mirrorless Sony con sensore Full-Frame CMOR Exmor 24.3 megapixel. Kit con obiettivo SEL 28-70 mm F3.5-5.6. Processore di immagini BIONZ X, 117 pt Fast Hybrid AF, 5 fps. ISO 100-51200, otturatore 1/8000-30 sec, batteria NPFW50 350 scatti. Registrazione video FHD 1080p, stabilizzazione integrata a 5 assi. La breve distanza della flangia posteriore negli obiettivi con attacco E dell\'α7 II consente un\'ampia compatibilità',
                'sconto' => '',
                'marca' => 'Sony',
                'immagine' => '14.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 449.00,
                'nome' => 'Sony Alpha 6000L ',
                'desc_breve' => 'Sony Alpha 6000L Kit Fotocamera Digitale Mirrorless con Obiettivo Intercambiabile',
                'desc_esaustiva' => 'Sony Alpha 6000L fotocamera digitale compatta, obiettivo intercambiabile, sensore APS-C CMOS Exmor HD da 24.3 MP, obiettivo da 16-50 mm e nero. Più grande è il sensore e migliori sono le immagini, e l\'α6000 surclassa molte fotocamere della sua categoria. Il sensore APS-C è 1,6 volte più grande dei sensori 4/3 e 13 volte più grande di quelli da 1/2,3\" delle tipiche digitali compatte. Il risultato è una qualità eccezionale in ogni immagine.Fotocamera digitale Mirrorless Sony con sensore APS-C CMOR Exmor 24.3 megapixel.Kit con obiettivo SEL 16-50 mm, Mirino OLED Tru-Finder ad alta risoluzione, Processore di immagini BIONZ X, 179 punti Eye AF, Flash integrato, display 3\" LCD inclinabile 180°, Compatibilità obiettivi: attacco E di Sony',
                'sconto' => 20,
                'marca' => 'Sony',
                'immagine' => '15.jpg',
                'sottocategoria' => 1
            ],
            ['prezzo' => 12499.00,
                'nome' => 'Sony PXW-FS7 ',
                'desc_breve' => 'La videocamera professionale Sony PXW-FS7 Mark II + 18-110mm è un sistema di telecamere 4K ',
                'desc_esaustiva' => 'L\'unità FS7 II è dotata di un sensore CMOS Exmor Super 35mm 4K Single-Chip, che offre immagini con una profondità di campo cinematografica. La fotocamera è dotata di un attacco E che non arrugginisce e offre un potente bloccaggio di tutti gli obiettivi. Potrà essere utilizzato qualsiasi obiettivo con innesto E, tutte le connessioni elettriche sono supportate. I video 4K o UHD fino a 60fps o HD fino a 180fps possono essere archiviati su schede di memoria XQD. È inoltre possibile scegliere di memorizzare le immagini in XVAC-I XVAC-L o MPEG-2. Inoltre, gli slot per schede di memoria two-XQD offrono la possibilità di effettuare registrazioni simultanee o relay. Sensore CMOS Exmor Super 35mm 4K a chip singolo. Videocamera per professionisti 4K (4096 x 2160) e UHD (3840 x 2160) a 60 fps. Video HD fino a 180 fps per super slow motion. Due slot per schede di memoria XQD. Funzionamento comodo ed ergonomico. Filtro ND variabile elettronico incorporato (regolabile tra 2 e 7 stop). 2x uscite HD / 3G-SDI e 1 x uscita HDMI. Registra la videocamera Sony per PrimeSupportPro',
                'sconto' => 20,
                'marca' => 'Sony',
                'immagine' => '16.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 3628.00,
                'nome' => 'Canon EOS C100 ',
                'desc_breve' => 'L\'offerta Canon EOS C100 Mark II+EF 18-135mm IS STM unisce le prestazioni della fotocamera compatta',
                'desc_esaustiva' => 'La fotocamera EOS C100 Mark II è una versione aggiornata della tecnologia C100 Dual Pixel CMOS AF che abilita una messa a fuoco continua con obiettivi Canon compatibili. Questo assicura un autofocus più veloce e accurato per aiutare gli utenti quando lavorano con piccoli team. Oltre all\'autofocus Dual Pixel CMOS AF, il Mark II presenta una grande varietà di funzionalità potenziate tra cui il riconoscimento facciale AF, la registrazione MP4, formati extra in ripresa AVCHD, opzioni di ripresa accelerata e al rallentatore in MP4. Il Mark II ha anche un microfono addizionale sul corpo macchina per registrare i suoni quando la maniglia superiore viene rimossa, oltre a uno schermo da 3.5 pollici OLED a risoluzione aumentata; il EVF è ora il doppio dell\'originale ed è inclinabile. Il Mark II supporta il GPS ed ha una funzionalità wireless incorporata. L\'uscita HDMI supporta la funzione time code, come l\'originale C100, oltre alal funzione Canon Log LUT. L\'EOS C100 Mark II utilizza lo stesso sensore Super 35mm Canon CMOS del suo fratello maggiore, il C300, ma ha un processore Digic DV 4. Grazie all\'attacco EF, la macchina è compatibile con l\'intera gamma degli obiettivi EF Canon EF, EF-S e EF Cinema. Questo si rivela paerticolarmente utile per i fotografi DSLR che hanno già investito negli obiettivi Canon. La fotocamera utilizza l\'AVCHD codec per video da 1080p fino a 24 M bps. Sono supportate le schede di memoria dual SD / SDHC / SDXC, che grazie al codec AVCHD consente di registrare almeno tre ore di video HD su ogni scheda da 32 GB. Per le applicazioni professionali, puoi registrare video non compressi 4: 2: 2 con time code incorporato via uscita HDMI.',
                'sconto' => 23,
                'marca' => 'Canon',
                'immagine' => '17.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 1199.00,
                'nome' => 'SeaLife DC2000 ',
                'desc_breve' => 'Il set di flash è un pacchetto completo contenente SeaLife DC2000 e un flash Sea Dragon Sea Dragon',
                'desc_esaustiva' => 'La fotocamera è impermeabile fino a 18 metri e con alloggiamento fino a 60 metri. Grazie a un ampio sensore di immagine da 20 megapixel retroilluminato Sony e alla registrazione RAW, il DC2000 offre risultati eccellenti. Quando si riprende sott\'acqua si sa che un buon flash è l\'accessorio più importante per realizzare registrazioni meravigliosamente colorate. Grazie al flash SeaLife SeaDragon i colori di foto e video saranno fantastici. Sensore di immagine da 1 pollice Sony da 20 megapixel per foto e video nitidi. Formati JPEG e RAW. Velocità dell\'otturatore e apertura regolabili manualmente da F1.8 a F11 in 17 fermate. 3 filtri colorati integrati per la correzione del colore digitale subacquea. 4 impostazioni subacquee con correzione del colore integrata. Continuous Burst acquisisce 8 scatti al secondo ad alta risoluzione. La profondità massima è di 60 metri. Wifi per trasferimento wireless e condivisione file',
                'sconto' => '',
                'marca' => 'SeaLife',
                'immagine' => '18.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 5749.00,
                'nome' => 'Blackmagic URSA Mini Pro 4.6K G2 ',
                'desc_breve' => 'La Blackmagic è una videocamera digitale di nuova generazione con elettronica aggiornata',
                'desc_esaustiva' => 'La fotocamera offre un sensore super-35mm per 4.6K con una gamma dinamica di 15 fotogrammi, filtri ND ottici integrati e un innesto di cambio EF, che è intercambiabile con montaggi opzionali PL, B4 o F. Include anche RAW e ProRes in Blackmagic e consente la registrazione diretta su unità esterne con la sua innovativa porta di espansione USB-C. Inoltre, URSA Mini Pro 4.6K G2 si distingue per numerosi controlli esterni tipici della trasmissione, un display di stato retroilluminato, un touchscreen pieghevole e altro ancora.LCD da 4 \"con touchscreen capacitivo, dimensioni effettive del sensore: 25,34 mm x 14,25 mm (Super 35), gamma dinamica 15 f-stop, innesto EF con innesto obiettivo incluso (intercambiabile con innesti opzionali PL, B4 e F) . Dettagli tecnici: Dimensioni effettive del sensore: 25,34 mm x 14,25 mm (Super 35) Attacco obiettivo: attacco EF incluso (sostituibile con supporti PL, B4 e F opzionali). Controllo del diaframma: controllo elettronico di obiettivi compatibili attraverso i poli sull\'EF -Monto o porta di trasmissione a 12 pin Gamma dinamica: 15 f-stop. Filtri ND integrati: rotella filtro ND per impostare le quattro posizioni possibili del filtro ND in f-stop: \"Clear\" (nessun filtro), \"2 stop\", \"4 stop\" e \" 6 arresti \". Messa a fuoco: il pulsante di messa a fuoco attiva la funzione di picco (autofocus disponibile su obiettivi compatibili). Controllo del diaframma: rotella del diaframma e cursore del touchscreen per la regolazione manuale dell\'obiettivo controllabile elettronicamente; Pulsante di apertura • Per le impostazioni di apertura automatica istantanea di obiettivi compatibili per evitare pixel ritagliati in modalità \"filmato\". Esposizione automatica basata sul contrasto medio della scena in modalità \"Video\" Dimensioni dello schermo: 4 pollici.>Tipo di schermo: LCD con touchscreen capacitivo. Supporto dei metadati: acquisizione automatica dei dati dell\'obiettivo di obiettivi elettronici EF, B4 e compatibili con tecnologia i / tecnologia; memorizzazione automatica delle impostazioni della fotocamera e dei dati dei file di film come progetto, numero di scena, riprese e note speciali. Controlli: menu touchscreen su schermo da 4 pollici. Pulsanti per funzioni aggiuntive; 2 tasti di scelta rapida assegnabili. Generatore di codice temporale: generatore di codice temporale ad alta precisione, la deviazione di temporizzazione ogni 8 ore è inferiore a un fotogramma',
                'sconto' => '',
                'marca' => 'Blackmagic',
                'immagine' => '19.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 2649,
                'nome' => 'CANON LEGRIA GX10 ',
                'desc_breve' => 'Filmati 4K straordinari anche senza treppiede e controllo creativo di livello professionale',
                'desc_esaustiva' => 'Crea storie d\'incredibile qualità 4K: Questa videocamera 4K 50p è dotata di messa a fuoco Dual Pixel CMOS AF, slow motion a 100 fps in Full HD, Wide DR e due slot per schede di memoria per creare storie di qualità professionale. Riprendi in formato 4K: riprendi filmati in 4K a 50p incredibilmente vivaci con la funzione Wide DR, anche nelle situazioni più difficili, grazie alle ottiche di precisione, allo zoom da 15x, all\'ampio sensore e al filtro ND da 8 stop. Qualità professionale: riprendi a mano libera in modo semplice grazie alla leva zoom professionale, alla ghiera dell\'obiettivo, all\'ampio touch screen orientabile con messa a fuoco Dual Pixel CMOS AF e alla potente stabilizzazione dell\'immagine. Controlli semplici e personalizzabili: prendi il controllo grazie ai pulsanti e alle ghiere facilmente personalizzabili e al telecomando wireless incluso oppure ottieni immediatamente eccezionali risultati in 4K con la modalità automatica. Cattura l\'azione: riprendi filmati in 4K a 50p, per fluidità e realismo straordinari. Crea fantastici slow motion a 50 fps in 4K e fino a 100 fps in Full HD. Sfrutta la registrazione continua su due schede di memoria per sessioni prolungate e backup.Semplice flusso di lavoro, elevata qualità audio: condividi contenuti via wireless e riprendi da remoto utilizzando il tuo dispositivo smart con Wi-Fi dual band. Aggiungi audio di alta qualità grazie all\'ingresso audio da 3,5 mm e alla mini slitta avanzata Canon.',
                'sconto' => '',
                'marca' => 'Canon',
                'immagine' => '20.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 1099.90,
                'nome' => 'Blackmagic Micro Cinema ',
                'desc_breve' => 'La più piccola cinepresa digitale al mondo con telecomando innovativo, una cinepresa digitale',
                'desc_esaustiva' => 'Usa il telecomando integrato per catturare azioni ovunque. Uno slot di modulo integrato rivoluzionario, chiamato porta di espansione, ha ingressi PWM e S.BUS, consentendo l\'utilizzo di un telecomando per aeromodelli e di un controllo wireless della telecamera. Difficile da immaginare: la regolazione wireless di messa a fuoco, apertura e zoom. La Micro Cinema Camera è una vera videocamera digitale che registra in RAW e ProRes. Trionfa con una gamma dinamica di 13 f-stop e un innesto obiettivo MFT. Come una vera macchina da presa digitale, viene utilizzata dove altre macchine da presa digitali non possono competere!. Realizza scatti d\'azione sensazionali. La Blackmagic Micro Cinema Camera è una fotocamera digitale incredibilmente piccola e di classe professionale, perfetta per l\'uso su quadrocopter, come crash cam o come telecamera nascosta sul set per i reality show. Può essere montato praticamente ovunque, compresi skateboard o alianti per riprese di sport estremi o un drone per creare scatti di pan-bird da una vista dall\'alto. O fissa la fotocamera su un casco per creare fantastici scatti POV! Il tuo pubblico sarà colpito dalla Blackmagic Micro Cinema Camera ed esclamerà: \"Wow, come è nata questa ripresa?\". Sensore Super 16mm La risoluzione Full 1080 full HD a 16 sensori della fotocamera Blackmagic Micro Cinema ha un\'incredibile gamma dinamica di 13 frame. D. h. Ottieni registrazioni con la vera qualità di un film digitale, perché il sensore acquisisce più informazioni nelle aree chiare e scure delle registrazioni. La DSLR e le action cam sono limitate ai contenuti video che tagliano luci e ombre. La Blackmagic Micro Cinema Camera, d\'altra parte, ti dà luci più luminose, senza toni di ritaglio, e i più piccoli dettagli nelle ombre. Con un valore ISO fino a 1600, ottieni la migliore qualità dell\'immagine anche in ambienti a bassa esposizione.Registratore RAW e ProRes integrato Il registratore incorporato registra in modalità di registro a 12 bit reale nella qualità di film digitale reale senza il rumore tipico dei file H.264 a 8 bit altamente compressi su azioni di piccole dimensioni e DSLR Le telecamere si verificano. I file possono essere salvati nei formati Cinema DNG RAW o ProRes. I file Cinema DNG RAW funzionano in modalità registro a 12 bit e forniscono tutti i dati acquisiti dal sensore della videocamera, il che significa che hai la libertà di modificare impostazioni come il bilanciamento del bianco e l\'esposizione molto dopo la fine della registrazione. Se hai bisogno di file più piccoli e durate di registrazione più lunghe, puoi lavorare con ProRes in qualità di trasmissione. Entrambi i formati possono essere comodamente tagliati e corretti per colore in DaVinci Resolve,incluso per Mac e Windows.',
                'sconto' => 20,
                'marca' => 'Blackmagic',
                'immagine' => '21.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 1379.00,
                'nome' => 'Blackmagic Pocket Cinema 4K MFT ',
                'desc_breve' => 'La videocamera Blackmagic Pocket Cinema 4K MFT ha sensore 4/3, gamma dinamica di 13 stop',
                'desc_esaustiva' => 'I comandi esterni ti danno immediato accesso a funzioni chiave, mentre il topuchscreen da 5 pollici rende facile la messa a fuoco, le operazioni di crop e la regolazione della videocamera. Le caratteristiche includono un registratore incorporato per SD/UHS-II o una scheda CFast 2.0 per registrazioni RAW o ProRes e un\'espansione USB-C per la registrazione su supporto di memoria esterno. La macchina è dotata di attacco micro quattro terzi, microfoni incorporati, connettore mini-XLR, una porta HDMI, supporto 3D LUT, Bluetooth e altre funzionalità. Videocamera Pocket Cinema 4K. Professionale, portabile e dal prezzo accessibile. Touchscreen da 12.7 cm (5 pollici). ISO fino a 25,600. Attacco micro quattro terzi con contorllo elettronico dell\'iride. Prestazioni eccellenti anche con poca luce',
                'sconto' => 50,
                'marca' => 'Blackmagic',
                'immagine' => '22.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 1969.00,
                'nome' => 'JVC GY-HM250E ',
                'desc_breve' => 'Con la videocamera Ultra HD Streaming 4K di JVC GY-HM250E puoi registrare 4K Ultra HD',
                'desc_esaustiva' => 'L\'obiettivo zoom 12x integrato e il sensore 4K CMOS offrono immagini Ultra HD nitide che possono essere registrate direttamente su schede di memoria SDHC / SDXC. Allo stesso tempo, il camcorder ha una tecnologia di streaming dual codec avanzata. Questa fotocamera ha anche una modalità teleobiettivo per ottenere oggetti nitidi a distanza ravvicinata e può visualizzare titoli grafici sia nella parte inferiore dello schermo che nell\'intera immagine. Sensore CMOS singolo da 1 / 2,3 pollici con 12,4 milioni di pixel (9,03 attivi). Zoom dinamico in modalità HD, combina lo zoom ottico e la mappatura dei pixel per creare uno zoom 24x continuo senza perdita di qualità. Registrazione 4: 2: 2 in full HD a 50 Mbps (24-60p). Registrazione HD a rallentatore 120fps. Uscita video UHD 4K in diretta, tramite HDMI. Filtro ND con 2 posizioni (1/4, 1/16). Uscite HD-SDI (3G) e HDMI (solo 4K da HDMI). 2x slot SDHC / SDXC per doppia,backup e registrazione continua. Avanzata tecnologia di streaming JVC, compatibile con la tecnologia di streaming USTREAM, Zixi e Wowza. Controllo remoto tramite rete (IP), visualizzazione remota, elaborazione dei metadati, upload di clip FTP (richiesta connessione e adattatore di rete corretti). Microfono stereo incorporato. Display LCD a colori da 3,5 pollici (920K pixel) con funzione di assistenza alla messa a fuoco intelligente. Mirino a colori da 0,24 pollici (1,56 M pixel) con funzione di assistenza alla messa a fuoco intelligente. Supporto per un telecomando cablato. 9 pulsanti utente programmabili. Include la sezione maniglia e la batteria SSL-JVC50 da 7,4 V, adattatore CA. Funzioni di trasmissione. Sovrapposizioni grafiche personalizzabili (on / off). Opzione per i loghi, la filigrana, il tempo e la temperatura personalizzati dell\'emettitore. Loghi precaricati selezionabili. Obiettivo zoom 12x F1.2-3.5 integrato. (equivalente 35 mm: 29.5354 mm). Scheda Ultra HD 4K (150 Mbps, 24 / 30p) su scheda SDXC (UHS-I Speed ​​Class 3). Microfono esterno e Wi-Fi o LTE Dongle non inclusi',
                'sconto' => '',
                'marca' => 'JVC',
                'immagine' => '23.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 2.247,
                'nome' => 'PANASONIC AG-UX180 ',
                'desc_breve' => 'La videocamera è dotaata di funzioni e specifiche professionali per operatori esperti.',
                'desc_esaustiva' => 'Il camcorder supporta la registrazione multiformato in 4K a 24p, UHD a 60p/50p, FHD a 60p/50p e la modalità Super Slow-Motion HD. Due slot per schede di memoria SD*1 consentono la registrazione relay/simultanea/di riserva, per un\'affidabilità superiore, mentre la possibilità di registrare a doppio codec UHD/FHD assicura un flusso di lavoro più efficiente.I comandi dell\'AG-UX180, come ad esempio le tre ghiere manuali e il pulsante dell\'utente, nonché le interfacce, quali gli ingressi 3G-SDI/HDMI e XLR, sono stati progettati per soddisfare le esigenze della videoregistrazione professionale. Con lo stesso livello di agilità e mobilità di un camcorder palmare HD tradizionale, l\'AG-UX180 supporta efficacemente la produzione di video in 4K a un\'elevata qualità dell\'immagine.Il grandangolo più ampio del settore (24 mm)*2 e l\'obiettivo con zoom ottico 20x di nuova concezione. Il primo*3 zoom ottico 20x al mondo in un camcorder con sensore da 1\"*4: l\'obiettivo con zoom ottico da 20x copre la gamma da 24 mm, all\'estremità del grandangolo, fino a 480 mm, all\'estremità telescopica (equivalente a pellicola da 35 mm in 4K a 24p).Sistema di obiettivi 4-Drive: gestisce simultaneamente e in modo indipendente 4 gruppi ottici (gruppo 2, diaframma, gruppo 3, gruppo 4) Le dimensioni dell\'obiettivo e l\'intervallo di azionamento di ciascuno dei 4 gruppi si possono ridurre con efficienza per ottimizzare la qualità dell\'immagine e la potenza dello zoom, garantendo allo stesso tempo un corpo compatto.Il grandangolo più ampio del settore, con 24 mm*5: l\'obiettivo integrato vanta il grandangolo più ampio del settore (24 mm) nell\'impostazione grandangolare. Questa caratteristica consente di effettuare riprese panoramiche con la minima distorsione, senza dover ricorrere a obiettivi di conversione, e inoltre di registrare/produrre video su veicoli o in interni, ad esempio. Zoom intelligente per ingrandimenti massimi di 30x a risoluzione super-elevata: nelle modalità di ripresa FHD, la funzione i.Zoom aumenta la capacità dello zoom fino a circa 30x, pur mantenendo una risoluzione elevata. Quando raggiunge il limite di 20x dello zoom ottico, il camcorder passa direttamente a i.Zoom.Zoom digitale (2x, 5x o 10x): l\'AG-UX180 offre uno zoom digitale da 2x, 5x e 10x. Se si utilizza lo zoom ottico 20x in combinazione con i.Zoom, si ottiene un ingrandimento da superteleobiettivo fino a 300x, senza perdite di intensità luminosa. Obiettivo LEICA DICOMAR*6: questo obiettivo ha superato i rigorosi standard qualitativi di Leica Camera AG. Un processo di rivestimento multiplo riduce al minimo gli effetti ghost e flare, creando immagini di estrema nitidezza.',
                'sconto' => '',
                'marca' => 'Panasonic',
                'immagine' => '24.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 1559.99,
                'nome' => 'PANASONIC AG-AC30',
                'desc_breve' => 'La AG-AC30 è una videocamera palmare con eccellenti caratteristiche',
                'desc_esaustiva' => 'La sua luce video a LED con 2 filtri di luce incluso permette di tiro affidabile anche nelle scene notturne e luoghi oscuri come il filtro di conversione colore adatta la temperatura di colore, mentre il filtro diffusore ammorbidisce la fonte di luce. Le caratteristiche di scarsa illuminazione in circolazione della videocamera è il risultato del sensore BSI 1 / 3.1-tipo built-in, di nuova concezione, che raggiunge una elevata qualità delle immagini di 6.03M pixel effettivi. Ciò consente luminose, belle inquadrature anche in luoghi bui. Modello: AG-AC30. Dimensioni schermo: 3 pollici. Dispone di stabilizzatore di immagini: Sì. Zoom ottico: 20 X. Touch Panel: 460K puntini 3.0 di tipo LCD. Cam remoto: Focus IRIS & Zoom S / S. Risoluzione sensore ottico: 6.03 MP. Risoluzione immagine: 1920 x 1080 Full HD. Risoluzione Video: 1920 x 1080 Full HD. Live Video Frame Rate: 60/100 fps. Display LCD. Tipo di sensore: 1 / 3.1-tipo BSI sensore MOS. Connettività: HDMI / USB 2.0 / XLR Analog Mic / Line Switchable (Phantom Power) . Tipo di Storage: SDHC / SDXC. Formati immagini supportati: DCF / EXIF / JPEG. Formati video supportati: AVCHD / MOV / MPEG-4. Colore Nero. Dimensioni prodotto: 170 x 170 x 335 mm.',
                'sconto' => 12,
                'marca' => 'Panasonic',
                'immagine' => '25.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 4980.00,
                'nome' => 'SONY PXW-FS5 ',
                'desc_breve' => 'Super35 CMOS Sensor, 3840 x 2160p Video, 100BASE-TX/10BASE-T LAN',
                'desc_esaustiva' => 'Se usi un camcorder portatile, dovresti poterti muovere ovunque. Lavorare da seduto. Seguire il set. Effettuare riprese da angolazioni insolite con eguale agilità. In più, una telecamera portatile deve funzionare perfettamente anche appoggiata al torace, o tenuta ferma senza difficoltà con la mano destra, con tutti i comandi a portata di mano. La straordinaria PXW-FS5 di Sony è tutto questo e molto altro. L\'FS5 è una rivisitazione radicale dell\'FS7, e offre riprese in movimento senza precedenti nelle condizioni più difficili. Grazie a un corpo che pesa meno della metà della FS7 (0,8 kg), puoi riprendere praticamente ovunque. Il funzionamento a mano è semplicemente eccezionale, dato che lo chassis bilanciato può essere configurato con semplicità ad angolazioni alte e basse, grazie all\'impugnatura flessibile e rotante e al viewfinder LCD, che può essere montato in nove diverse posizioni. E come avviene spesso con i prodotti di Sony, per fornire un controllo completo sull\'illuminazione nelle situazioni in rapido movimento, abbiamo inventato il primo filtro ND elettronico variabile per un camcorder Super 35 mm. Quando sei sul campo, è importante cogliere subito ogni opportunità, non c\'è tempo da perdere. L\'FS5 consente di aggiungere o rimuovere rapidamente i componenti come l\'impugnatura e il viewfinder LCD senza strumenti speciali, mentre i fori per le viti da 1/4\" supportano il montaggio su un drone, un supporto gimbal o in una custodia subacquea. Il sistema α-Mount di Sony offre una compatibilità insuperabile sia con le ottiche di Sony che di terzi. L\'E-Mount della FS5 è compatibile con gli obiettivi cinematografici ed SLR grazie all\'uso di un adattatore di terze parti, oltre che con le ottiche E-Mount e A-Mount di Sony, per semplificare al massimo l\'utilizzo di ottiche nuove o acquistate precedentemente. Quando la qualità è prioritaria, sfrutta appieno il sensore Exmor della FS5 Super 35 e riprendi in 4K a 100 Mbps (3840 x 2160), avvalendoti del sistema di registrazione XAVC avanzato (Long GOP) di Sony. In futuro sarà disponibile un\'opzione per registrare esternamente file RAW (dettagli ancora da annunciare). Se invece ciò che cerchi è la rapidità, passa alle riprese Full HD (1920 x 1080) in formato XAVC fino a 60p 10 bit 4:2:2 a 50 Mbps. L\'FS5 ha la flessibilità di adattarsi al modo in cui desideri lavorare, oggi come domani. Le riprese in High Frame Rate possono trasformare l\'azione di ogni giorno in una danza in slow motion, e l\'FS5 è in grado di offrire l\'incredibile frame rate di 240 fps in Full HD XAVC 10 bit 4:2:2. Se il progetto si avvale di un frame rate cinematografico di 24p, puoi utilizzare la bellissima funzione super slow motion 10x. Non è necessario scendere a compromessi in termini di bit di profondità e non si crea l\'indesiderato effetto di \"windowing\" del sensore, pertanto non sono visibili ritagli né perdite nell\'angolazione.',
                'sconto' => '',
                'marca' => 'Sony',
                'immagine' => '26.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 1669.00,
                'nome' => 'Panasonic HC-X1000E ',
                'desc_breve' => 'Videocamera Professionale, 4K Ultra HD, 60p/50p, Zoom ottico 20x, Nero',
                'desc_esaustiva' => 'Risoluzione a 60p/50p che garantisce un\'incredibile qualità delle immagini 4K. A questo livello la frequenza dei fotogrammi video ha il doppio delle informazioni rispetto a 30p/25p migliorando in questo modo la fluidità della registrazione. Registrazione con alto Bit Rate sia in 4K che in Full HD. Funzioni professionali: obiettivo LEICA Dicomar, triplo anello per regolazioni manuali, 2 slot per SD, filtro ND, 2 ingressi microfonici XLR. Zoom ottico 20x con stabilizzatore ottico di immagine a 5 assi. Contenuto confezione: videocamera HC-X1000E, caricabatteria, cavo per caricabatteria, batteria al litio ricaricabile CGA-D54,cavo HDMI compatibile 4K, cavo USB, supporto microfono, tracolla. Software editing. Videocamera Full HD con registrazione in 4K 60p/50p su SD Card;. funzioni professionali;. Lenti LEICA Dicomar;zoom ottico 20x,sensore BSI 1/2.3\".Vari formati di registrazione: 4k/Cinema 4k/Full HD, frame rate possibili 60p/50p/20p; cavo HDMI compatibile 4K incluso, 2 ingressi microfonici XLR. Filtro ND selezionabile, corpo compatto ideale per riprese professionali e documentari; Funzione Wi-Fi con NFC; Stabilizzatore di immagine a 5 assi; 2 slot per SD; Triplo anello per regolazioni manuali: fuoco, zoom, diaframma;NTSC/PAL;',
                'sconto' => '',
                'marca' => 'Panasonic',
                'immagine' => '27.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 1885.33,
                'nome' => '1885.33 ',
                'desc_breve' => 'La Sony nex-vg20eh una videocamera ad alta definizione con un obiettivo intercambiabile',
                'desc_esaustiva' => 'Riprese in qualità Full HD con massima flessibilità creativa grazie agli obiettivi intercambiabili. Per foto e video dettagliati con bassa profondità di campo come con una videocamera DSLR. Massima qualità del suono con canale 5.1. Qualità da cinema. Godetevi la qualità dei vostri video HD con immagini perfette anche con scarse condizioni di illuminazione, effetti affascinanti di sfondo e qualità sorprendente come una videocamera DSLR.Più obiettivi, più creatività. I fotografi professionisti sanno come è importante scegliere l\'obiettivo giusto in ogni situazione. Adesso anche voi avrete a disposizione possibilità illimitate. Scegliete l\'obiettivo giusto per la scena da riprendere. Per un audio migliore. Per dialoghi chiari e suoni perfetti con il microfono Quad Capsule Spatial Array e l\'audio surround a 5.1 canali. Pratica regolazione del volume e collegamenti per microfono esterno e cuffie, per dare al dispositivo un aspetto professionale. Massimo controllo. Impostazioni manuali precise per illuminazione, iride, bilanciamento dei bianchi e altre opzioni. Rotella programmabile, tasti di accesso rapido e touchscreen luminoso per fare in modo che sia facile adattare le impostazioni senza dover interrompere la fase creativa. Dispositivo di qualità, leggero e affidabile. Grazie a Sony tutti potranno godersi immagini di alta qualità. Ergonomia ottimizzata.',
                'sconto' => '',
                'marca' => 'Sony',
                'immagine' => '28.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 157.00,
                'nome' => 'Panasonic HC-V180EG-K  ',
                'desc_breve' => 'Videocamera Full HD (sensore da 1/5, 8 pollici, Full HD, zoom ottico 50x, grandangolo da 28 mm ',
                'desc_esaustiva' => 'PANASONIC HC-V180EG-K Full HD, Sensore BSI 1/5,8\'\', Zoom intelligent 90x, Zoom ottico 50x, Funzione livella e stabilizzatore 5-axis, Grandangolo 28mm. Se di tanto in tanto filmate in vacanza o ad eventi speciali, l\'HC-V180 con la sua qualità Full HD e automatismi intelligenti è perfetto. Con uno zoom ottico 50x e uno zoom intelligente 77x, evidenzia i dettagli del motivo. Lo stabilizzatore ottico delle immagini assicura che i tuoi scatti non siano sfocati. Un\'intera gamma di modalità creative trasforma anche le tue registrazioni in videoclip originali. Con il rilevamento delle vibrazioni a 5 assi, grazie a questa videocamera puoi realizzare filmati stabili e nitidi mentre scopri nuovi paesaggi o ti diverti con la famiglia. È fondamentale ai livelli di zoom più elevati e per compensare le vibrazioni della videocamera. Il pratico obiettivo grandangolare da 28 mm permette di realizzare anche splendidi paesaggi e foto di gruppo. Zoom: Intelligent 90x e ottico 50x. L\'Intelligent Zoom 90x consente di immortalare facilmente oggetti troppo distanti da riprendere con le funzioni di zoom tradizionali. È anche possibile usare lo zoom ottico 50x per aggiungere alle riprese più emozioni e dinamismo',
                'sconto' => 5,
                'marca' => 'Panasonic',
                'immagine' => '29.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 2072.21,
                'nome' => 'SONY Videocamera HXR-NX80 ',
                'desc_breve' => 'Ultra HD Sensore CMOS 14.2 MP Zoom Ottico 12x LCD Touch Panel 3.5" Colore Nero',
                'desc_esaustiva' => 'L’HXR-NX80 è il primo camcorder ultra-compatto professionale in grado di offrire contenuto HDR (High Dynamic Range) 4K straordinario, con workflow basati su file HLG (Hybrid Log-Gamma). Supporta anche S-Log3, per creare splendide immagini con vasta gamma di colori. L’HXR-NX80 offre un incredibile frame rate di 120 fotogrammi al secondo (fps) in Full HD XAVC S a 10 bit 4:2:0, per slow motion continuo massimo di 5x. Frame rate più elevati fino a 960 fps con registrazione cache S&Q Motion, per una maggiore flessibilità creativa. ipo sensore: CMOS. Zoom ottico: 12x, Lunghezza focale: 9,3 - 111,6 mm, Lente equivalente da 35 mm: 32,8 - 393,6 mm. Tipo di supporto videocamera: Scheda di memoria, Tipi schede di memoria: SD, SDHC, SDXC. Regolazione messa a fuoco: Auto / Manuale, Distanza minima di focus: 0,01 m. Bilanciamento del bianco: Auto, Interno, One push, Esterno. Colore del prodotto: Nero.',
                'sconto' => 15,
                'marca' => 'Sony',
                'immagine' => '30.jpg',
                'sottocategoria' => 2
            ],
            ['prezzo' => 329.00,
                'nome' => 'GoPro HERO8  ',
                'desc_breve' => ' Fotocamera digitale impermeabile 4K con stabilizzazione ipersfondata, touch screen',
                'desc_esaustiva' => 'Hero8 black è la fotocamera hero più versatile e più ferma di sempre. Il design semplificato la rende più tascabile che mai e la sostituzione dei supporti richiede pochi secondi, grazie alle guide pieghevoli integrate. E l\'unità multimediale opzionale permette di ottenere la massima espandibilità per aggiungere più illuminazione, audio di livello professionale e persino un altro schermo. Dotata della sbalorditiva funzione slo-mo, hero8 black ti offre inoltre la rivoluzionaria stabilizzazione hypersmooth 2.0. Video: 4k60, 2,7k120, 1440p120, 1080p240, ecc. / registrazione di video in loop / effetto slow motion 8x foto: 12 mp / foto singola / foto notturna / liveburst / sequenza 30 fps / raw per ottenere costantemente i risultati migliori con la videocamera gopro, è importante scegliere schede microsd dalla compatibilità comprovata. Consigliamo di acquistare solo schede microsd di marca tramite i rivenditori ufficiali. La forma rivisitata è più tascabile e le guide pieghevoli alla base ti permettono di sostituire i supporti in pochi attimiVlogger, filmmaker professionisti e aspiranti creator possono sbizzarrirsi grazie ad accessori a caricamento rapido come flash, microfoni, schermi lcd e altro ancora. Ancora più fluido; hero8 black ha ora tre livelli di stabilizzazione (on, alto e boost), quindi puoi scegliere l\'opzione migliore per te; ottieni la visuale più ampia possibile o aumenta il livello di stabilizzazione per ottenere i video più fluidi mai offerti da una fotocamera hero. Registra video temporizzati ultra stabilizzati mentre ti muovi durante un\'attività; inoltre, timewarp regola automaticamente la velocità in base al movimento, al rilevamento delle scene e all\'illuminazione. Cattura straordinarie foto da 12 mp con hdr migliorato, sia in movimento che da fermo, con sfocatura ridotta e dettagli vividi anche in aree con scarsa illuminazione',
                'sconto' => '',
                'marca' => 'GoPro',
                'immagine' => '37.jpg',
                'sottocategoria' => 3
            ],
            ['prezzo' => 62.99,
                'nome' => 'Crosstour CT9500 ',
                'desc_breve' => '4K30FPS Action Cam 20MP WiFi Action Camera(40M Impermeabile Fotocamera Subacquea',
                'desc_esaustiva' => 'Descrizione del prodotto crosstour ct9500 offre una varietà di funzioni e caratteristiche diverse. Risoluzione ottima. Risoluzione 4k 20mp (nuova funzione anti-shake) 4k (30fps) può registrare ogni momento importante della tua vita creando video distinti. 20 mp aiuteranno a scattare foto ultra chiare. Questo modello ha anche la nuova funzione anti-shake che rimane stabile durante le riprese e la registrazione. Prestazione antipolvere impermeabile avanzata la custodia impermeabile 40m offre una protezione eccezionale e prestazioni stabili per gli sport acquatici, come immersioni, surf o nuoto. Fa foto col rallentatore e registrazione in loop la registrazione al rallentatore darà alla fotocamera la possibilità di osservare video lunghi (alba, tramonto) in un breve periodo di tempo. La registrazione in loop è una modalità di registrazione continua che consente di utilizzare la action camera come una dash cam durante la guida. Suggerimenti utili si prega di formattare la scheda micro sd (non inclusa) nella fotocamera prima dell\'uso. Specifiche tecniche risoluzione video 4k(30fps) 2.7k(30fps) 1440p(60/30fps) 1080p(60/30fps) 720p(120/60fps)risoluzione foto: 20mp, 16mp, 12mp, 5mp, 3mplenti: 170°a+ alta risoluzione grandangolo lenti con sette-livelli di vetrof/1.8 larga apertura sony imx377 sensoreconnessione wi-fi android/ios supportainterfaccia usb: micro usbbatterie: 2 rimuovibili 3.7v 1350mah li-ion batteriescafandro impermeabileprofondità: 40m/131.3ftdimensioni: 614524mm/2.41”x1.78”x0.95”tempo di ricarica: fino a 90 minutimemoria: 8 - 128gb micro sd card supporta.richiede class 10+ (non inclusa) contenuto crosstour action camera ct95002 batterie ricaricabili (1350mah)caricatore batteria usbscafandro impermeabilecover antipolverecavo usb.',
                'sconto' => 52,
                'marca' => 'Crosstour',
                'immagine' => '38.jpg',
                'sottocategoria' => 3
            ],
            ['prezzo' => 49.99,
                'nome' => 'APEMAN Action Cam A77',
                'desc_breve' => '4K 20MP Wi-Fi Impermeabile 30M con Telecomando fotocamera subacquea digitale,Hyper Stabilizzatore',
                'desc_esaustiva' => 'Risoluzione 4K Ultra HD Action Camera professionale Apeman 4K Ultra HD registra video in 4K/30fps e scatta foto da 20MP, quattro volte piu’ vantaggioso delle camere precedenti. Scatta e condividi il tuo mondo con una risoluzione magnifica. Telecomando Wireless dotato di un telecomando 2.4GHz a polso, puoi scattare le tue foto in qualsiasi situazione. Registrare video, scattare foto o inquadrare il tuo scatto non e’ stato cosi facile con il telecomando. Impermeabilita’ fino a 30 metri di profondita’La cassa impermeabile e’ creata per esplorare l’affascinante mondo sottomarino tramite sport come: nuoto, immersione, surf, drifting e altro, anche tramite competizoni estreme. Il tutto accompagnato da 20 fantastici accessori, che ti permettera’ di utilizzare la camera come vuoi tu. Incorporato di WiFi e HDMI L’action camera e’ compatibile con IOS e Android. Controlla la camera tramite il tuo smartphone, rivedi le foto e i video a tempo reale e trasferisci i file sul telefono in modo da poter condividerle sui social media via DV KING 4K. Il segnale WiFi ha un raggio di 10 metri.',
                'sconto' => 29,
                'marca' => 'Apeman',
                'immagine' => '39.jpg',
                'sottocategoria' => 3
            ],
            ['prezzo' => 17.87,
                'nome' => 'Treppiede MKCOMPACTACN-BK  ',
                'desc_breve' => 'Treppiede con Borsa, Testa Ibrida per Fotografia e Video, 5 Sezioni in Alluminio, Nero',
                'desc_esaustiva' => 'Il treppiedi è stato progettato per funzionare con DSLR entry level con obiettivi standard, ma è compatibile anche con qualsiasi dispositivo fino a 1.5 Kg come fotocamere compatte, CSC e Bridge. Inoltre, la rotellina di regolazione, insieme alla piastra a sgancio rapido rotonda consente di regolare ogni fotocamera al treppiede rafforzando in tal modo la sua stabilità. Nato per essere sempre con te. Molto leggero, portatile e facile da usare, il Compact Light è il treppiedi inedito per ogni circostanza. Ottieni l\'ottimo dalla tua fotocamera. Borsa protettiva. Borsa imbottita per un trasporto comodo e sicuro. Compattezza e semplicità: Flessibile, leggero e ottimo per reflex e mirrorless. Stabilità: Immagini nitide e dettagliate grazie alla solida struttura delle gambe.',
                'sconto' => 27,
                'marca' => 'Manfrotto',
                'immagine' => '40.jpg',
                'sottocategoria' => 4
            ],
            ['prezzo' => 39.99,
                'nome' => ' Treppiedi TP-35',
                'desc_breve' => 'Treppiedi Fotocamera Alluminio Compatto Treppiede Leggero Per Canon Nikon Sony Olympus DSLR DV',
                'desc_esaustiva' => 'ESDDI è un marchio che si è dedicato al settore dell\'attrezzatura fotografica.Noi si impegna a migliorare l\'esperienza degli utenti fornendo prodotti di buona qualità . Noi considera le tue opinioni, ognuno di voi verrà considerato seriamente quando acquisterà i nostri prodotti. Materiali: Tubi in lega di Alluminio, Plastica ABS per la protezione ambientale. Testa: 3 Vie. Folded length: 63cm. Altezza Massima del Treppiede:170cm.Diametro Massimo dei Tubi: 23mm. Quantità Colonne: 3 Sezioni. Capacità di Carico: 4kg. Peso: 1.35kg La piastra a sgancio rapido è dotata di clip e tappetino in gomma, per fissare e staccare facilmente la fotocamera. Il livello della bolla permette di regolare il tubo per aiutarLa a raggiungere la posizione di livello.',
                'sconto' => 13,
                'marca' => 'ESDDI',
                'immagine' => '41.jpg',
                'sottocategoria' => 4
            ],
            ['prezzo' => 21.99,
                'nome' => 'Treppiedi 1.72M  ',
                'desc_breve' => 'Treppiede Smartphone Cavalletto per Cellulare, iPhone, Fotocamera, Proiettore',
                'desc_esaustiva' => 'Stabile: realizzato in treppiede lega di alluminio di buona qualità, molto leggero, peso del carico massimo 3.0 KG.Allungabile: la dimensione piegata è di 41 cm, la dimensione estesa è di 125 cm, adatta per il viaggio.Compatibile con tutti i tipi di fotocamera: Canon, Nikon, Sony, Panasonic, Olympus, Leica, Fujifilm, Kodak e altre reflex, SLR e DSLR.Compatibile con smartphone: iPhone, Huawei, Samsung, Xiaomi, LG e altri cellulare con supporto telefono universale con cold shoe.Compatibile con Gopro, actioncam, mini proiettore, macchina fotografica sportiva con adattatore Gopro, con telecomando bluetooth per smartphone per foto e video. Materiale di qualità. Fatto di lega di alluminio. Peso netto: 0.65 KG. Leggero ma durevole. Altezza flessibile. Altezza minima: 41 cm. Altezza massima: 125 cm. Portatile e facile da portare in viaggioPied antiscivolo. Testa a 360 gradi. Supporto orizzontale foto e video di 360 gradi. Supporto verticale foto e video di 270 gradiSupporto laterali foto e video. Foto orizzontale.Compatibile con camera reflex: Canon, Nikon, Sony, Panasonic, Olympus, Leica, Fujifilm, Kodak e altre macchina fotografica con fotocamera universale.Compatibile con Gopro con adattatore de Gopro.Foto verticaleCompatibile con smartphone: iPhone 4/5/5s/se/ 6/6s/7/7s/8 e plus e iPhone X, 11, 11pro, Huawei honor, mate, pro, Samsung, Xiaomi, LG e altri smartphone con supporto cellulare universale con cold shoe e telecomando bluetooth per foto e video.Compatibile con mini proiettore, video proiettore',
                'sconto' => '',
                'marca' => 'Phnistec',
                'immagine' => '42.jpg',
                'sottocategoria' => 4
            ],
            ['prezzo' => 137.00,
                'nome' => 'Huawei Mediapad T3  ',
                'desc_breve' => 'Tablet Wi-Fi, CPU Quad-Core A53, 2 GB RAM, 16 GB, Display da 10 Pollici, EMUI 5.1 (Android N),Grigio',
                'desc_esaustiva' => 'Design elegante, viste luminose. Tocca la potenza del design brillante con il tuo HUAWEI MediaPad T3 10. Guarda il mondo con colori vivaci grazie al vivido display da 9,6 pollici. Tocca la qualità del corpo unibody in alluminio anodizzato utilizzato in aeronautica. Vedi con chiarezza. HUAWEI MediaPad T3 10 è lì per te, giorno e notte. Le speciali modalità a bassa luminosità e protezione occhi ti assicurano di avere una visione completa della tua vita, riducendo l\'affaticamento degli occhi e aiutando a preservare il tuo modello di sonno naturale. Gioia che dura. Distinguiti, esci, HUAWEI MediaPad T3 10 è il tuo fedele compagno, giorno e notte. La batteria di lunga durata farà in modo di disporre degli strumenti necessari per tutto il tempo necessario. Porta con te la tua famiglia. L\'accesso intelligente alle app e il controllo dei contenuti ti consentono di consentire ad altri di utilizzare il tuo dispositivo in modo da avere il pieno controllo. Sia che lasci che i bambini giochino, che condividano il dispositivo o che ti impediscano di distrarti, sei il padrone.',
                'sconto' => 3,
                'marca' => 'Huawei',
                'immagine' => '31.jpg',
                'sottocategoria' => 5
            ],
            ['prezzo' => 419.90,
                'nome' => 'Xiaomi Mi Note 10 ',
                'desc_breve' => '6 GB RAM + 128 GB ROM, Schermo 3D Curved Amoled 6.47", Penta Camera 108 MP, 5260 mAh, Aurora',
                'desc_esaustiva' => 'Mi Note 10 è dotato di una fotocamera da 108 MP con una risoluzione fotografica fino a 12032 x 9024, 12 volte la risoluzione 4K. Con un sensore di immagine da 1/1,33\", la fotocamera di Mi Note 10 cattura tutti i dettagli di paesaggi mozzafiato. Mi Note 10 impiega una tecnologia di sblocco dello schermo ultra sottile e ottimizza ulteriormente l\'esperienza di sblocco in condizioni estreme come luce intensa, dita asciutte e basse temperature. Sperimenta uno sblocco ultra sensibile e reattivo. Smartphone con Penta camera da 108 MP per risultati da professionista. Selfie camera da 32 MP. Il display curvo da 6.47” AMOLED FHD+ offre una elevata risoluzione e colori vividi. Sensore di impronte digitali integrato nello schermo, preciso e affidabile. Memoria RAM. da 6 GB e memoria interna da 128 GB. Processore Qualcomm Snapdragon 730G 8 nm. Batteria da 5260 mAh ad alta capacità con alimentatore a carica rapida da 30 W incluso nella confezione.',
                'sconto' => '',
                'marca' => 'Xiaomi',
                'immagine' => '32.jpg',
                'sottocategoria' => 6
            ],
            ['prezzo' => 999.00,
                'nome' => 'LG Gram Laptop 15Z990 ',
                'desc_breve' => 'Display 15.6" Full HD IPS, Processore i5-8265U, RAM 8 GB DDR4, SSD 512 GB, Grafica UHD 620',
                'desc_esaustiva' => 'Lavora senza pensieri per tutto il giorno. La batteria da 72Wh ti consente di lavorare anche in movimento senza doverti preoccupare di collegare il dispositivo alla presa di corrente. Display IPS Full HD da 15,6\". Un\'esperienza visiva ancora più emozionante. Lo schermo IPS garantisce una straordinaria qualità dell’immagine con una definizione di livello superiore. Lo schermo Full HD (1920X1080) unito alla gamma di colori con sRGB superiore al 96% permette di effettuare una regolazione cromatica ancora più precisa. Processore Intel Core i5-8265U (1.6 GHz, Turbo fino a 3.9 GHz, L3 cache 6 MB, 15 W) Display 15.6\" IPS FullHD (1920 x 1080), RAM 8 GB DDR4 (2400 MHz), 512 GB SSD. Chassis in lega di magnesio e nano carbon per una struttura solida e leggera (peso 1099 g). Batteria litio a lunga durata 72 Wh, fino 21.5 ore di autonomia. Tastiera retroilluminata, layout Italiano, accesso rapido con impronta digitale. Interfaccia USB-C/Thunderbolt 3 (video, dati, alimentazione).Durabilità certificata: standard militare MIL-STD 810 G. Dimensioni: 357.6 x 14.5-16.8 x 228.4 mm',
                'sconto' => '',
                'marca' => 'LG',
                'immagine' => '33.jpg',
                'sottocategoria' => 7
            ],
            ['prezzo' => 547.79,
                'nome' => 'HP Desktop 285 ',
                'desc_breve' => 'Windows 10 Pro, AMD Ryzen 5 PRO, 8 GB di RAM, SSD da 256, Nero',
                'desc_esaustiva' => 'HP Desktop 200 hanno un accurato case, con un design compatto ed efficiente.Sono affidabili e sicuri: computer potenti con prestazioni scalabili per crescere insieme all\'azienda.Con la potenza del processore che ottimizza il tempo di risposta del sistema e la velocità di caricamento dei file, ti permetterà di mantenere le prestazioni dei tuoi computer al massimo della potenza. Windows 10 Pro. Per assicurare il futuro del tuo business sfrutta al meglio Windows 10 Pro, per la protezione contro le odierne minacce alla sicurezza e ottimizzano le funzioni di gestione e produttività per le aziende.Espandere il proprio lavoro. Il valore del tuo investimento è accresciuto dalle possibilità di espansione, che aumentano la durata del computer. Inoltre può diventare un comodo hub per tutti i dispositivi dell\'ufficio, fino a porte USB a disposizione, per essere sempre connessi.Certificazione ENERGY STAR EPEAT:HP HP Desktop 200 contribuisce a ridurre il consumo di energia abbassando i costi, aumentando l\'efficenza energetica grazie alla classificazione EPEAT. Valuta gli standard ambientali del ciclo di vita del prodotto e classifica prodotti come oro, argento o bronzo basandosi su criteri di prestazioni ambientali. Processore AMD Ryzen 5 2400G Quad-Core con scheda grafica Radeon RX Vega 11 (frequenza di base 3.2 GHz); chipset AMD B350. Memoria 8 GB di SDRAM DDR4-2666 (1 da 8 GB); sSD PCIe NVMe da 256 GB; masterizzatore DVD SATA. I PC HP sfruttano al meglio Windows 10 Pro per la protezione contro le attuali minacce alla sicurezza e ottimizzano le funzioni di gestione e produttività per le aziende. Godetevi un\'esperienza desktop completa con HP 285 MT, un PC scalabile, facile da installare e utilizzare e dotato di un design funzionale ottimo per l\'area di lavoro. Mettete la produttività al primo posto e trasferite rapidamente i file o aggiungete storage temporaneo grazie al lettore di schede SD, ora di serie su HP 285 MT',
                'sconto' => 15,
                'marca' => 'Hp',
                'immagine' => '34.jpg',
                'sottocategoria' => 8
            ],
            ['prezzo' => 379.99,
                'nome' => 'Samsung UE43RU7450UXZT ',
                'desc_breve' => ' Smart TV 4K Ultra HD 43", Wi-Fi DVB-T2CS2, 3840 x 2160 Pixels',
                'desc_esaustiva' => 'Grazie alla tecnologia Dynamic Crystal Color potrai immergerti in immagini con un miliardo di colori e goderti un illimitato realismo, senza perdere nemmeno la minima sottigliezza.I TV Samsung UHD sono certificati per la vera qualità UHD 4K e offrono un\'esperienza visiva di qualità superiore grazie al sistema HDR Powered by HDR 10+. La tecnologia High Dynamic Range amplia l’intervallo tra aree più chiare e aree più scure, in modo da offrirti una gamma immensa di colori e dettagli visivi anche nelle scene più buie. Un singolo chip orchestra infatti i colori, ottimizza l’elevato contrasto e gestisce l’HDR, regalandoti una qualità e un dettaglio delle immagini che sanno emozionare.Con i tv Samsung UHD metti fine alle lunghe ricerche: con la Universal Guide del tuo tv Samsung potrai trovare i tuoi contenuti preferiti in modo rapido e semplice; memorizza ciò che ti piace e avrai in un’unica schermata tutti i tuoi contenuti preferiti. (Universal Guide: solo Regno Unito, Francia, Germania, Italia e Spagna).In pochi attimi puoi collegare il tuo TV Samsung ad altoparlanti e altri dispositivi smart (da Alexa di Amazon, Google Assistant, Airplay di Apple e ogni altro dispositivo compatibile con l’app Samsung SmartThings) e avere tutti i contenuti a portata di mano con un unico telecomando grazie al One Remote Control. L’app Samsung SmartThings è integrata nel tuo Samsung UHD TV, che così può connettersi ai tuoi dispositivi e sensori IoT. Accendere le luci, controllare cosa c’è nel frigo e anche gestire l’aspirapolvere robot: puoi fare tutto dal TV. I dispositivi compatibili con SmartThings possono variare in base alla regione. Con Clean Cable Solution, poi, potrai nascondere i collegamenti e goderti al meglio il tuo TV seguendo tre semplici passaggi: Passaggio 1. Collega i cavi. Passaggio 2. Inserisci i collegamenti nell’apposito passacavi integrato nella parte posteriore. Passaggio 3. Organizza i cavi all\'interno della base del TV. Tutto in ordine, nascosto completamente.',
                'sconto' => 37,
                'marca' => 'Samsung',
                'immagine' => '35.jpg',
                'sottocategoria' => 9
            ],
            ['prezzo' => 129.90,
                'nome' => 'Acer SA240YAbi ',
                'desc_breve' => 'Monitor FreeSync, 23,8", Display IPS Full HD, 75 Hz, 4 ms, 16:9',
                'desc_esaustiva' => 'DESIGN SOTTILE E ALLA MODA: l design sottile ed elegante assicura che il monitor sia piacevole alla vista e conceda maggiore spazio allo schermo, mentre la base lo rende ottimo in ogni posizione. DESIGN ZEROFRAME: Ottimo divertimento e ottima visibilità dello schermo grazie al design senza cornice.TECNOLOGIA IPS: Grazie agli ampi angoli di visione e alla tecnologia IPS puoi condividere le immagini con chi ti sta attorno. TUTELA DELLA VISTA: La tecnologia Acer BlueLightShield riduce l\'esposizione della luce blu regolando luminosità e tonalità dei colori e la tecnologia Acer ComfyView riduce la quantità di luce riflessa RISOLUZIONE FULL HD: Guarda immagini chiare e nitide grazie alla risoluzione Full HD (1920x1080) di questo monitor Acer. Acer FLICKERLESS: La tecnologia Acer Flickerless elimina lo sfarfallio dello schermo attraverso la fornitura di un\'alimentazione stabile al display. Design sottile Il design sottile ed elegante assicura che il monitor sia piacevole alla vista e conceda maggiore spazio allo schermo.Supporto alla moda. La base elegante, con il suo motivo a cerchi concentrici, è perfetta in ogni posizione. ZeroFrame. Ottimo divertimento e ottima visibilità dello schermo grazie al design senza cornice. Tutti possono guardare. Grazie agli ampi angoli di visione e alla tecnologia IPS puoi condividere le immagini con chi ti sta attorno.',
                'sconto' => '',
                'marca' => 'Acer',
                'immagine' => '36.jpg',
                'sottocategoria' => 10
            ]
        ]);
    }

}
